package com.comvee.cdms.differentlevels.po;


public class MemberDifferentLevelsPO {
    /**
     * 主键
     */
    private String sid;

    /**
     * 患者编号
     */
    private String memberId;

    /**
     * 患者名称
     */
    private String memberName;

    /**
     * 患者名称拼音
     */
    private String memberNamePy;

    /**
     * 性别
     */
    private Integer sex;

    /**
     * 年龄
     */
    private Integer age;

    /**
     * 层级是否改变 1是 0否
     */
    private Integer layerChange;

    /**
     * 改变日期
     */
    private String changeDate;

    /**
     * 改变日期时间
     */
    private String changeDt;

    /**
     * 分级 1 一级支持 2 二级支持 3 三级支持
     */
    private Integer level;

    /**
     * 分层 1 高危层 2 中危层 3 平稳层
     */
    private Integer layer;

    /**
     * 是否确认 1已经确认（不再提醒）0未确认（提醒）
     */
    private Integer read;

    /**
     * 记录是否有效 1有 0否
     */
    private Integer isValid;

    /**
     * 入库时间
     */
    private String insertDt;

    /**
     * 更新时间
     */
    private String modifyDt;

    /**
     * 来源 1 系统 2 手动添加 3 其他
     */
    private Integer origin;

    /**
     * 来源编号（医生编号，HIS-医院编号）
     */
    private String originId;

    /**
     * 确认人编号（医生编号） 
     */
    private String doctorId;

    /**
     * 是否调整 0 不调整 1调整
     */
    private Integer adjustment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.sid
     *
     * @return the value of t_member_different_levels.sid
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.sid
     *
     * @param sid the value for t_member_different_levels.sid
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.member_id
     *
     * @return the value of t_member_different_levels.member_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.member_id
     *
     * @param memberId the value for t_member_different_levels.member_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.member_name
     *
     * @return the value of t_member_different_levels.member_name
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.member_name
     *
     * @param memberName the value for t_member_different_levels.member_name
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.member_name_py
     *
     * @return the value of t_member_different_levels.member_name_py
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getMemberNamePy() {
        return memberNamePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.member_name_py
     *
     * @param memberNamePy the value for t_member_different_levels.member_name_py
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setMemberNamePy(String memberNamePy) {
        this.memberNamePy = memberNamePy == null ? null : memberNamePy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.sex
     *
     * @return the value of t_member_different_levels.sex
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.sex
     *
     * @param sex the value for t_member_different_levels.sex
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.age
     *
     * @return the value of t_member_different_levels.age
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.age
     *
     * @param age the value for t_member_different_levels.age
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.layer_change
     *
     * @return the value of t_member_different_levels.layer_change
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getLayerChange() {
        return layerChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.layer_change
     *
     * @param layerChange the value for t_member_different_levels.layer_change
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setLayerChange(Integer layerChange) {
        this.layerChange = layerChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.change_date
     *
     * @return the value of t_member_different_levels.change_date
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.change_date
     *
     * @param changeDate the value for t_member_different_levels.change_date
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setChangeDate(String changeDate) {
        this.changeDate = changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.change_dt
     *
     * @return the value of t_member_different_levels.change_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getChangeDt() {
        return changeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.change_dt
     *
     * @param changeDt the value for t_member_different_levels.change_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setChangeDt(String changeDt) {
        this.changeDt = changeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.level
     *
     * @return the value of t_member_different_levels.level
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.level
     *
     * @param level the value for t_member_different_levels.level
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.layer
     *
     * @return the value of t_member_different_levels.layer
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.layer
     *
     * @param layer the value for t_member_different_levels.layer
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.read
     *
     * @return the value of t_member_different_levels.read
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.read
     *
     * @param read the value for t_member_different_levels.read
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.is_valid
     *
     * @return the value of t_member_different_levels.is_valid
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.is_valid
     *
     * @param isValid the value for t_member_different_levels.is_valid
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.insert_dt
     *
     * @return the value of t_member_different_levels.insert_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.insert_dt
     *
     * @param insertDt the value for t_member_different_levels.insert_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.modify_dt
     *
     * @return the value of t_member_different_levels.modify_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.modify_dt
     *
     * @param modifyDt the value for t_member_different_levels.modify_dt
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.origin
     *
     * @return the value of t_member_different_levels.origin
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.origin
     *
     * @param origin the value for t_member_different_levels.origin
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.origin_id
     *
     * @return the value of t_member_different_levels.origin_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getOriginId() {
        return originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.origin_id
     *
     * @param originId the value for t_member_different_levels.origin_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setOriginId(String originId) {
        this.originId = originId == null ? null : originId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.doctor_id
     *
     * @return the value of t_member_different_levels.doctor_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.doctor_id
     *
     * @param doctorId the value for t_member_different_levels.doctor_id
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.adjustment
     *
     * @return the value of t_member_different_levels.adjustment
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public Integer getAdjustment() {
        return adjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.adjustment
     *
     * @param adjustment the value for t_member_different_levels.adjustment
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setAdjustment(Integer adjustment) {
        this.adjustment = adjustment;
    }
}