package com.comvee.cdms.differentlevels.po;

public class MemberDifferentLevelsPOWithBLOBs extends MemberDifferentLevelsPO {
    /**
     * 理由JSON
     */
    private String reasonJson;

    /**
     * 对比分析描述（调整原因）
     */
    private String caDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.reason_json
     *
     * @return the value of t_member_different_levels.reason_json
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getReasonJson() {
        return reasonJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.reason_json
     *
     * @param reasonJson the value for t_member_different_levels.reason_json
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setReasonJson(String reasonJson) {
        this.reasonJson = reasonJson == null ? null : reasonJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_different_levels.ca_desc
     *
     * @return the value of t_member_different_levels.ca_desc
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public String getCaDesc() {
        return caDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_different_levels.ca_desc
     *
     * @param caDesc the value for t_member_different_levels.ca_desc
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    public void setCaDesc(String caDesc) {
        this.caDesc = caDesc == null ? null : caDesc.trim();
    }
}