package com.comvee.cdms.machine.mapper;

import com.comvee.cdms.machine.model.ThpMemberMachine;
import com.comvee.cdms.machine.model.ThpMemberMachineExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThpMemberMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    long countByExample(ThpMemberMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int deleteByExample(ThpMemberMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int insert(ThpMemberMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int insertSelective(ThpMemberMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    List<ThpMemberMachine> selectByExample(ThpMemberMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    ThpMemberMachine selectByPrimaryKey(Long sid);
    
    
    List<ThpMemberMachine> selectByModel(ThpMemberMachine model);
    
//    ThpMemberMachine selectByMemberIdAndDeviceType(@Param("memberId") String memberId,@Param("machineType") String machineType);
//
//    ThpMemberMachine selectByMemberIdAndMachineId(@Param("memberId") String memberId,@Param("machineId") String machineId);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ThpMemberMachine record, @Param("example") ThpMemberMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int updateByExample(@Param("record") ThpMemberMachine record, @Param("example") ThpMemberMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int updateByPrimaryKeySelective(ThpMemberMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thp_member_machine
     *
     * @mbg.generated Tue Jul 24 09:30:09 CST 2018
     */
    int updateByPrimaryKey(ThpMemberMachine record);
    
    /**
     * 绑定设备
     * @param record
     */
    void bindEquipment(ThpMemberMachine record);
    
    /**
     * 解除绑定设备
     * @param record
     */
    void unBindEquipment(ThpMemberMachine record);
    
    /**
	 * 根据machineId查询是否绑定
	 * @param machineId
	 * @return
	 */
    Long countMachineByMachineId(@Param("machineId") String machineId);
}