package com.comvee.cdms.qualitycontrol.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quality_control
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class QualityControlPO {
    /**
     * 主键id
     * sid
     */
    private String sid;

    /**
     * 测量血糖值
     * measure_value
     */
    private String measureValue;

    /**
     * 测量日期
     * measure_dt
     */
    private String measureDt;

    /**
     * 测量结果
     * measure_result
     */
    private Integer measureResult;

    /**
     * 试纸批号
     * paper_batch_no
     */
    private String paperBatchNo;

    /**
     * 质控液批号
     * liquid_batch_no
     */
    private String liquidBatchNo;

    /**
     * 级别编号
     * level_code
     */
    private Integer levelCode;

    /**
     * 级别名称
     * level_name
     */
    private String levelName;

    /**
     * 范围最小值
     * range_min
     */
    private String rangeMin;

    /**
     * 范围最大值
     * range_max
     */
    private String rangeMax;

    /**
     * 设备号
     * machine_sn
     */
    private String machineSn;

    /**
     * 设备id
     * machine_id
     */
    private String machineId;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 医院id
     * hospital_id
     */
    private String hospitalId;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.sid
     *
     * @return the value of t_quality_control.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.sid
     *
     * @param sid the value for t_quality_control.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.measure_value
     *
     * @return the value of t_quality_control.measure_value
     *
     * @mbggenerated
     */
    public String getMeasureValue() {
        return measureValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.measure_value
     *
     * @param measureValue the value for t_quality_control.measure_value
     *
     * @mbggenerated
     */
    public void setMeasureValue(String measureValue) {
        this.measureValue = measureValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.measure_dt
     *
     * @return the value of t_quality_control.measure_dt
     *
     * @mbggenerated
     */
    public String getMeasureDt() {
        return measureDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.measure_dt
     *
     * @param measureDt the value for t_quality_control.measure_dt
     *
     * @mbggenerated
     */
    public void setMeasureDt(String measureDt) {
        this.measureDt = measureDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.measure_result
     *
     * @return the value of t_quality_control.measure_result
     *
     * @mbggenerated
     */
    public Integer getMeasureResult() {
        return measureResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.measure_result
     *
     * @param measureResult the value for t_quality_control.measure_result
     *
     * @mbggenerated
     */
    public void setMeasureResult(Integer measureResult) {
        this.measureResult = measureResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.paper_batch_no
     *
     * @return the value of t_quality_control.paper_batch_no
     *
     * @mbggenerated
     */
    public String getPaperBatchNo() {
        return paperBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.paper_batch_no
     *
     * @param paperBatchNo the value for t_quality_control.paper_batch_no
     *
     * @mbggenerated
     */
    public void setPaperBatchNo(String paperBatchNo) {
        this.paperBatchNo = paperBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.liquid_batch_no
     *
     * @return the value of t_quality_control.liquid_batch_no
     *
     * @mbggenerated
     */
    public String getLiquidBatchNo() {
        return liquidBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.liquid_batch_no
     *
     * @param liquidBatchNo the value for t_quality_control.liquid_batch_no
     *
     * @mbggenerated
     */
    public void setLiquidBatchNo(String liquidBatchNo) {
        this.liquidBatchNo = liquidBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.level_code
     *
     * @return the value of t_quality_control.level_code
     *
     * @mbggenerated
     */
    public Integer getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.level_code
     *
     * @param levelCode the value for t_quality_control.level_code
     *
     * @mbggenerated
     */
    public void setLevelCode(Integer levelCode) {
        this.levelCode = levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.level_name
     *
     * @return the value of t_quality_control.level_name
     *
     * @mbggenerated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.level_name
     *
     * @param levelName the value for t_quality_control.level_name
     *
     * @mbggenerated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.range_min
     *
     * @return the value of t_quality_control.range_min
     *
     * @mbggenerated
     */
    public String getRangeMin() {
        return rangeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.range_min
     *
     * @param rangeMin the value for t_quality_control.range_min
     *
     * @mbggenerated
     */
    public void setRangeMin(String rangeMin) {
        this.rangeMin = rangeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.range_max
     *
     * @return the value of t_quality_control.range_max
     *
     * @mbggenerated
     */
    public String getRangeMax() {
        return rangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.range_max
     *
     * @param rangeMax the value for t_quality_control.range_max
     *
     * @mbggenerated
     */
    public void setRangeMax(String rangeMax) {
        this.rangeMax = rangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.machine_sn
     *
     * @return the value of t_quality_control.machine_sn
     *
     * @mbggenerated
     */
    public String getMachineSn() {
        return machineSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.machine_sn
     *
     * @param machineSn the value for t_quality_control.machine_sn
     *
     * @mbggenerated
     */
    public void setMachineSn(String machineSn) {
        this.machineSn = machineSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.machine_id
     *
     * @return the value of t_quality_control.machine_id
     *
     * @mbggenerated
     */
    public String getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.machine_id
     *
     * @param machineId the value for t_quality_control.machine_id
     *
     * @mbggenerated
     */
    public void setMachineId(String machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.operator_id
     *
     * @return the value of t_quality_control.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.operator_id
     *
     * @param operatorId the value for t_quality_control.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.hospital_id
     *
     * @return the value of t_quality_control.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.hospital_id
     *
     * @param hospitalId the value for t_quality_control.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.insert_dt
     *
     * @return the value of t_quality_control.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.insert_dt
     *
     * @param insertDt the value for t_quality_control.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.update_dt
     *
     * @return the value of t_quality_control.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.update_dt
     *
     * @param updateDt the value for t_quality_control.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control.valid
     *
     * @return the value of t_quality_control.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control.valid
     *
     * @param valid the value for t_quality_control.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}