package com.comvee.cdms.qualitycontrol.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quality_control_material_config
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class QualityControlMaterialConfigPO {
    /**
     * sid
     */
    private String sid;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 医院id
     * hospital_id
     */
    private String hospitalId;

    /**
     * 配置数据（json）
     * config_data
     */
    private String configData;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.sid
     *
     * @return the value of t_quality_control_material_config.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.sid
     *
     * @param sid the value for t_quality_control_material_config.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.operator_id
     *
     * @return the value of t_quality_control_material_config.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.operator_id
     *
     * @param operatorId the value for t_quality_control_material_config.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.hospital_id
     *
     * @return the value of t_quality_control_material_config.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.hospital_id
     *
     * @param hospitalId the value for t_quality_control_material_config.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.config_data
     *
     * @return the value of t_quality_control_material_config.config_data
     *
     * @mbggenerated
     */
    public String getConfigData() {
        return configData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.config_data
     *
     * @param configData the value for t_quality_control_material_config.config_data
     *
     * @mbggenerated
     */
    public void setConfigData(String configData) {
        this.configData = configData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.insert_dt
     *
     * @return the value of t_quality_control_material_config.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.insert_dt
     *
     * @param insertDt the value for t_quality_control_material_config.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.update_dt
     *
     * @return the value of t_quality_control_material_config.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.update_dt
     *
     * @param updateDt the value for t_quality_control_material_config.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quality_control_material_config.valid
     *
     * @return the value of t_quality_control_material_config.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quality_control_material_config.valid
     *
     * @param valid the value for t_quality_control_material_config.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}