package com.comvee.cdms.remind.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_member_remind
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddMemberRemindDTO {

    /**
     * member_id
     */
    private String memberId;


    /**
     * 提醒类型
     * remind_type
     */
    private Integer remindType;

    /**
     * 数据json字符串
     * data_json_str
     */
    private String dataJsonStr;

    /**
     * 关联外键
     * foreign_id
     */
    private String foreignId;

    private String remindMessage;

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public Integer getRemindType() {
        return remindType;
    }

    public void setRemindType(Integer remindType) {
        this.remindType = remindType;
    }

    public String getDataJsonStr() {
        return dataJsonStr;
    }

    public void setDataJsonStr(String dataJsonStr) {
        this.dataJsonStr = dataJsonStr;
    }

    public String getForeignId() {
        return foreignId;
    }

    public void setForeignId(String foreignId) {
        this.foreignId = foreignId;
    }

    public String getRemindMessage() {
        return remindMessage;
    }

    public void setRemindMessage(String remindMessage) {
        this.remindMessage = remindMessage;
    }
}