package com.comvee.cdms.member.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_member_apply
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DoctorMemberApplyDTO {

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 医患关系创建方式 1 web端添加患者  2 APP添加患者 3 扫描二维码 4 小程序患者申请添加 5 筛查系统同步 6转诊添加医患关系
     */
    private Integer relationWay;

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public Integer getRelationWay() {
        return relationWay;
    }

    public void setRelationWay(Integer relationWay) {
        this.relationWay = relationWay;
    }
}