package com.comvee.cdms.member.dto;

import javax.validation.constraints.NotEmpty;
import java.io.Serializable;

/**
 * @author: wangxy
 * @date: 2018/10/29
 */
public class UpdateMemberDTO implements Serializable{

    @NotEmpty(message = "memberId 不能为空")
    private String memberId;

    /**
     * 患者姓名
     * member_name
     */
    private String memberName;

    /**
     * 患者姓名拼音
     * member_name_py
     */
    private String memberNamePy;

    private String memberNamePys;
    /**
     * 头像地址
     * pic_url
     */
    private String picUrl;

    /**
     * 手机号
     * mobile_phone
     */
    private String mobilePhone;

    /**
     * 性别 1男2女
     * sex
     */
    private Integer sex;

    /**
     * 出生日期
     * birthday
     */
    private String birthday;

    /**
     * 身份证号码
     * id_card
     */
    private String idCard;

    /**
     * 职业
     * profession
     */
    private String profession;

    /**
     * 糖尿病类型：1型SUGAR_TYPE_001)、2型(SUGAR_TYPE_002)、妊娠(SUGAR_TYPE_003)、其他(SUGAR_TYPE_004)	当糖尿病诊断选项选“确诊有”时出现糖尿病类型选项	是
     * diabetes_type
     */
    private String diabetesType;

    /**
     * 确诊日期
     * diabetes_date
     */
    private String diabetesDate;


    /**
     * 插入时间
     * insert_dt
     */
    private String insertDt;

    /**
     * 修改时间
     * modify_dt
     */
    private String modifyDt;

    /**
     * 身高
     * height
     */
    private String height;

    /**
     * 体重
     * weight
     */
    private String weight;

    /**
     * bmi
     * bmi
     */
    private String bmi;

    /**
     * 收缩压
     * blood_pressure
     */
    private String sbpPressure;
    /**
     * 舒张压
     * blood_pressure
     */
    private String dbpPressure;

    /**
     * 国家
     * country
     */
    private String country;

    /**
     * 详细地址
     * address
     */
    private String address;

    /**
     * 高血压:1有、2无
     * essential_hyp
     */
    private String essentialHyp;

    /**
     * 是否有冠心病:确诊有(QZ01)、确诊无(QZ02)、未评估(QZ03)、疑似（界面中不显示）(QZ04)
     * chd
     */
    private String chd;

    /**
     * 是否有糖尿病肾病:确诊有SB01、确诊无SB02、未确诊  未评估SB03疑似SB04
     * nephropathy
     */
    private String nephropathy;

    /**
     * 劳动强度 RCHDQD01：轻体力劳动 RCHDQD02：中体力劳动 RCHDQD03:重体力劳动 RCHDQD04:非劳动/卧床
     * labour_intensity
     */
    private String labourIntensity;

    /**
     * 心率
     * hreat_rate
     */
    private String hreatRate;

    /**
     * 患者详细信息
     * member_info
     */
    private String memberInfo;

    /**
     * 分层标识: 1平稳层、2中危层、3高危层
     * level_hx
     */
    private String levelHx;

    /**
     * 分级标识: 1级、2级、3级
     */
    private String dsmeHx;

    private String visitNo;

    /**
     * 是否有糖尿病 1:是 2:否
     */
    private String isDiabetes;

    /**
     *高血压类型 :原发性高血压:HYP_TYPE_001  继发性高血压:HYP_TYPE_002 其他:HYP_TYPE_003
     */
    private String hypType;

    /**
     * 高血压确诊日期
     * hypDate
     */
    private String hypDate;

    private String fat;

    /**
     * 用户标签
     */
    private String memberTag;

    /**
     * 1.口服降糖药
     * 2.胰岛素
     * 3.胰岛素+口服降糖药
     * 4.其他
     */
    private Integer treatment;
    private String socialCard;
    private String committeeId;
    private String committeeName;


    public String getMemberNamePys() {
        return memberNamePys;
    }

    public void setMemberNamePys(String memberNamePys) {
        this.memberNamePys = memberNamePys;
    }

    public String getFat() {
        return fat;
    }

    public void setFat(String fat) {
        this.fat = fat;
    }

    public String getIsDiabetes() {
        return isDiabetes;
    }

    public void setIsDiabetes(String isDiabetes) {
        this.isDiabetes = isDiabetes;
    }


    public String getVisitNo() {
        return visitNo;
    }

    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.member_id
     *
     * @return the value of t_member.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.member_id
     *
     * @param memberId the value for t_member.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.member_name
     *
     * @return the value of t_member.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.member_name
     *
     * @param memberName the value for t_member.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.member_name_py
     *
     * @return the value of t_member.member_name_py
     *
     * @mbggenerated
     */
    public String getMemberNamePy() {
        return memberNamePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.member_name_py
     *
     * @param memberNamePy the value for t_member.member_name_py
     *
     * @mbggenerated
     */
    public void setMemberNamePy(String memberNamePy) {
        this.memberNamePy = memberNamePy == null ? null : memberNamePy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.pic_url
     *
     * @return the value of t_member.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.pic_url
     *
     * @param picUrl the value for t_member.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.mobile_phone
     *
     * @return the value of t_member.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.mobile_phone
     *
     * @param mobilePhone the value for t_member.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.birthday
     *
     * @return the value of t_member.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.birthday
     *
     * @param birthday the value for t_member.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id_card
     *
     * @return the value of t_member.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id_card
     *
     * @param idCard the value for t_member.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.profession
     *
     * @return the value of t_member.profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.profession
     *
     * @param profession the value for t_member.profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.diabetes_type
     *
     * @return the value of t_member.diabetes_type
     *
     * @mbggenerated
     */
    public String getDiabetesType() {
        return diabetesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.diabetes_type
     *
     * @param diabetesType the value for t_member.diabetes_type
     *
     * @mbggenerated
     */
    public void setDiabetesType(String diabetesType) {
        this.diabetesType = diabetesType == null ? null : diabetesType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.diabetes_date
     *
     * @return the value of t_member.diabetes_date
     *
     * @mbggenerated
     */
    public String getDiabetesDate() {
        return diabetesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.diabetes_date
     *
     * @param diabetesDate the value for t_member.diabetes_date
     *
     * @mbggenerated
     */
    public void setDiabetesDate(String diabetesDate) {
        this.diabetesDate = diabetesDate == null ? null : diabetesDate.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.insert_dt
     *
     * @return the value of t_member.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.insert_dt
     *
     * @param insertDt the value for t_member.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.modify_dt
     *
     * @return the value of t_member.modify_dt
     *
     * @mbggenerated
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.modify_dt
     *
     * @param modifyDt the value for t_member.modify_dt
     *
     * @mbggenerated
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt == null ? null : modifyDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.height
     *
     * @return the value of t_member.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.height
     *
     * @param height the value for t_member.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.weight
     *
     * @return the value of t_member.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.weight
     *
     * @param weight the value for t_member.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.bmi
     *
     * @return the value of t_member.bmi
     *
     * @mbggenerated
     */
    public String getBmi() {
        return bmi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.bmi
     *
     * @param bmi the value for t_member.bmi
     *
     * @mbggenerated
     */
    public void setBmi(String bmi) {
        this.bmi = bmi == null ? null : bmi.trim();
    }

    public String getSbpPressure() {
        return sbpPressure;
    }

    public void setSbpPressure(String sbpPressure) {
        this.sbpPressure = sbpPressure;
    }

    public String getDbpPressure() {
        return dbpPressure;
    }

    public void setDbpPressure(String dbpPressure) {
        this.dbpPressure = dbpPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.country
     *
     * @return the value of t_member.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.country
     *
     * @param country the value for t_member.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.address
     *
     * @return the value of t_member.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.address
     *
     * @param address the value for t_member.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.essential_hyp
     *
     * @return the value of t_member.essential_hyp
     *
     * @mbggenerated
     */
    public String getEssentialHyp() {
        return essentialHyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.essential_hyp
     *
     * @param essentialHyp the value for t_member.essential_hyp
     *
     * @mbggenerated
     */
    public void setEssentialHyp(String essentialHyp) {
        this.essentialHyp = essentialHyp == null ? null : essentialHyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.chd
     *
     * @return the value of t_member.chd
     *
     * @mbggenerated
     */
    public String getChd() {
        return chd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.chd
     *
     * @param chd the value for t_member.chd
     *
     * @mbggenerated
     */
    public void setChd(String chd) {
        this.chd = chd == null ? null : chd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.nephropathy
     *
     * @return the value of t_member.nephropathy
     *
     * @mbggenerated
     */
    public String getNephropathy() {
        return nephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.nephropathy
     *
     * @param nephropathy the value for t_member.nephropathy
     *
     * @mbggenerated
     */
    public void setNephropathy(String nephropathy) {
        this.nephropathy = nephropathy == null ? null : nephropathy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.labour_intensity
     *
     * @return the value of t_member.labour_intensity
     *
     * @mbggenerated
     */
    public String getLabourIntensity() {
        return labourIntensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.labour_intensity
     *
     * @param labourIntensity the value for t_member.labour_intensity
     *
     * @mbggenerated
     */
    public void setLabourIntensity(String labourIntensity) {
        this.labourIntensity = labourIntensity == null ? null : labourIntensity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.hreat_rate
     *
     * @return the value of t_member.hreat_rate
     *
     * @mbggenerated
     */
    public String getHreatRate() {
        return hreatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.hreat_rate
     *
     * @param hreatRate the value for t_member.hreat_rate
     *
     * @mbggenerated
     */
    public void setHreatRate(String hreatRate) {
        this.hreatRate = hreatRate == null ? null : hreatRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.member_info
     *
     * @return the value of t_member.member_info
     *
     * @mbggenerated
     */
    public String getMemberInfo() {
        return memberInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.member_info
     *
     * @param memberInfo the value for t_member.member_info
     *
     * @mbggenerated
     */
    public void setMemberInfo(String memberInfo) {
        this.memberInfo = memberInfo == null ? null : memberInfo.trim();
    }

    public String getLevelHx() {
        return levelHx;
    }

    public void setLevelHx(String levelHx) {
        this.levelHx = levelHx;
    }

    public String getDsmeHx() {
        return dsmeHx;
    }

    public void setDsmeHx(String dsmeHx) {
        this.dsmeHx = dsmeHx;
    }

    public String getHypType() {
        return hypType;
    }

    public void setHypType(String hypType) {
        this.hypType = hypType;
    }

    public String getHypDate() {
        return hypDate;
    }

    public void setHypDate(String hypDate) {
        this.hypDate = hypDate;
    }

    public String getMemberTag() {
        return memberTag;
    }

    public void setMemberTag(String memberTag) {
        this.memberTag = memberTag;
    }

    public Integer getTreatment() {
        return treatment;
    }

    public void setTreatment(Integer treatment) {
        this.treatment = treatment;
    }

    public String getSocialCard() {
        return socialCard;
    }

    public void setSocialCard(String socialCard) {
        this.socialCard = socialCard;
    }

    public String getCommitteeId() {
        return committeeId;
    }

    public void setCommitteeId(String committeeId) {
        this.committeeId = committeeId;
    }

    public String getCommitteeName() {
        return committeeName;
    }

    public void setCommitteeName(String committeeName) {
        this.committeeName = committeeName;
    }
}
