package com.comvee.cdms.member.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_member_apply
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UpdateDoctorMemberApplyDTO {

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 状态 1 未处理 2 已同意 3 拒绝
     * apply_status
     */
    private Integer applyStatus;

    /**
     * 备注，理由
     * remark
     */
    private String remark;

    /**
     * 验证信息
     * check_info
     */
    private String checkInfo;

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public Integer getApplyStatus() {
        return applyStatus;
    }

    public void setApplyStatus(Integer applyStatus) {
        this.applyStatus = applyStatus;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getCheckInfo() {
        return checkInfo;
    }

    public void setCheckInfo(String checkInfo) {
        this.checkInfo = checkInfo;
    }
}