package com.comvee.cdms.follow.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_follow_custom_formwork
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class FollowCustomFormworkPO {
    /**
     * sid
     */
    private String sid;

    /**
     * 随访模板名称
     * follow_name
     */
    private String followName;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 创建者id
     * creator_id
     */
    private String creatorId;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 是否有效 1 有效 0 无效
     * valid
     */
    private Integer valid;

    /**
     * 选择的系统题目， 逗号隔开
     * question_str
     */
    private String questionStr;

    /**
     * 自定义添加的题目json
     * custom_question_data
     */
    private String customQuestionData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.sid
     *
     * @return the value of t_follow_custom_formwork.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.sid
     *
     * @param sid the value for t_follow_custom_formwork.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.follow_name
     *
     * @return the value of t_follow_custom_formwork.follow_name
     *
     * @mbggenerated
     */
    public String getFollowName() {
        return followName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.follow_name
     *
     * @param followName the value for t_follow_custom_formwork.follow_name
     *
     * @mbggenerated
     */
    public void setFollowName(String followName) {
        this.followName = followName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.doctor_id
     *
     * @return the value of t_follow_custom_formwork.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.doctor_id
     *
     * @param doctorId the value for t_follow_custom_formwork.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.creator_id
     *
     * @return the value of t_follow_custom_formwork.creator_id
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.creator_id
     *
     * @param creatorId the value for t_follow_custom_formwork.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.insert_dt
     *
     * @return the value of t_follow_custom_formwork.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.insert_dt
     *
     * @param insertDt the value for t_follow_custom_formwork.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.update_dt
     *
     * @return the value of t_follow_custom_formwork.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.update_dt
     *
     * @param updateDt the value for t_follow_custom_formwork.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.valid
     *
     * @return the value of t_follow_custom_formwork.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.valid
     *
     * @param valid the value for t_follow_custom_formwork.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_custom_formwork.question_str
     *
     * @return the value of t_follow_custom_formwork.question_str
     *
     * @mbggenerated
     */
    public String getQuestionStr() {
        return questionStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_custom_formwork.question_str
     *
     * @param questionStr the value for t_follow_custom_formwork.question_str
     *
     * @mbggenerated
     */
    public void setQuestionStr(String questionStr) {
        this.questionStr = questionStr;
    }

    public String getCustomQuestionData() {
        return customQuestionData;
    }

    public void setCustomQuestionData(String customQuestionData) {
        this.customQuestionData = customQuestionData;
    }
}