package com.comvee.cdms.follow.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_followup_care
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class FollowupCarePO {
    /**
     * sid
     */
    private String sid;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 关怀内容
     * care_content
     */
    private String careContent;

    /**
     * 发送日期
     * send_date
     */
    private String sendDate;

    /**
     * 发送状态 1 已发送 0 未发送
     * send_status
     */
    private Integer sendStatus;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 是否有效
     * valid
     */
    private Integer valid;

    /**
     * 发送者信息
     * sender_info
     */
    private String senderInfo;

    /**
     * 接收者类型 1 指定患者 2 全部患者
     * receive_type
     */
    private Integer receiveType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.sid
     *
     * @return the value of t_followup_care.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.sid
     *
     * @param sid the value for t_followup_care.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.member_id
     *
     * @return the value of t_followup_care.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.member_id
     *
     * @param memberId the value for t_followup_care.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.doctor_id
     *
     * @return the value of t_followup_care.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.doctor_id
     *
     * @param doctorId the value for t_followup_care.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.care_content
     *
     * @return the value of t_followup_care.care_content
     *
     * @mbggenerated
     */
    public String getCareContent() {
        return careContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.care_content
     *
     * @param careContent the value for t_followup_care.care_content
     *
     * @mbggenerated
     */
    public void setCareContent(String careContent) {
        this.careContent = careContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.send_date
     *
     * @return the value of t_followup_care.send_date
     *
     * @mbggenerated
     */
    public String getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.send_date
     *
     * @param sendDate the value for t_followup_care.send_date
     *
     * @mbggenerated
     */
    public void setSendDate(String sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.send_status
     *
     * @return the value of t_followup_care.send_status
     *
     * @mbggenerated
     */
    public Integer getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.send_status
     *
     * @param sendStatus the value for t_followup_care.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.insert_dt
     *
     * @return the value of t_followup_care.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.insert_dt
     *
     * @param insertDt the value for t_followup_care.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.update_dt
     *
     * @return the value of t_followup_care.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.update_dt
     *
     * @param updateDt the value for t_followup_care.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.valid
     *
     * @return the value of t_followup_care.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.valid
     *
     * @param valid the value for t_followup_care.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.sender_info
     *
     * @return the value of t_followup_care.sender_info
     *
     * @mbggenerated
     */
    public String getSenderInfo() {
        return senderInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.sender_info
     *
     * @param senderInfo the value for t_followup_care.sender_info
     *
     * @mbggenerated
     */
    public void setSenderInfo(String senderInfo) {
        this.senderInfo = senderInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup_care.receive_type
     *
     * @return the value of t_followup_care.receive_type
     *
     * @mbggenerated
     */
    public Integer getReceiveType() {
        return receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup_care.receive_type
     *
     * @param receiveType the value for t_followup_care.receive_type
     *
     * @mbggenerated
     */
    public void setReceiveType(Integer receiveType) {
        this.receiveType = receiveType;
    }
}