package com.comvee.cdms.follow.po;

import java.io.Serializable;

/**
 * 随访内容实体类
 * @author 林雨堆
 * @String 2018-03-28 10:00
 */
public class FollowupPO implements Serializable {
    /**
     * 主键
     */
    private String sid;

    /**
     * 是否有效 1有效 0无效
     */
    private Integer isValid;

    /**
     * 添加时间
     */
    private String insertDt;

    /**
     * 更新时间
     */
    private String modifyDt;

    /**
     * 患者信息
     */
    private String memberInfo;

    /**
     * 随访信息
     */
    private String followInfo;
    private String memberId;
    private Integer dealStatus;
    private String nextDt;

    /**
     * 随访教育者
     */
    private String doctorName;
    private String leaderId;
    /**
     * 用药数据
     */
    private String drugListJson;

    public String getNextDt() {
        return nextDt;
    }

    public void setNextDt(String nextDt) {
        this.nextDt = nextDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup.sid
     *
     * @return the value of t_followup.sid
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup.sid
     *
     * @param sid the value for t_followup.sid
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup.is_valid
     *
     * @return the value of t_followup.is_valid
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup.is_valid
     *
     * @param isValid the value for t_followup.is_valid
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup.insert_dt
     *
     * @return the value of t_followup.insert_dt
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup.insert_dt
     *
     * @param insertDt the value for t_followup.insert_dt
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followup.modify_dt
     *
     * @return the value of t_followup.modify_dt
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followup.modify_dt
     *
     * @param modifyDt the value for t_followup.modify_dt
     *
     * @mbggenerated Wed Mar 28 09:56:04 CST 2018
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt;
    }

    public String getMemberInfo() {
        return memberInfo;
    }

    public void setMemberInfo(String memberInfo) {
        this.memberInfo = memberInfo;
    }

    public String getFollowInfo() {
        return followInfo;
    }

    public void setFollowInfo(String followInfo) {
        this.followInfo = followInfo;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getMemberId() {
        return memberId;
    }

    public Integer getDealStatus() {
        return dealStatus;
    }

    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public String getLeaderId() {
        return leaderId;
    }

    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId;
    }

    public String getDrugListJson() {
        return drugListJson;
    }

    public void setDrugListJson(String drugListJson) {
        this.drugListJson = drugListJson;
    }
}