package com.comvee.cdms.follow.po;

import java.io.Serializable;

/**
 * 随访主表
 * @author 林雨堆
 * @date 2018-03-27 11：00
 */
public class MainFollowPO implements Serializable {
    private String sid;

    /**
     * 1首诊  2日常随访 3自我行为问卷 4糖尿病足随访表(深圳) 5糖尿病随访表(深圳)
     */
    private Integer type;

    /**
     * 随访类型 1默认 2华西随访
     */
    private Integer followType;

    /**
     * 下次随访时间
     */
    private String nextDt;

    /**
     * 填表人：1 医生 2 患者
     */
    private Integer fillFormBy;

    /**
     * 状态 0 未完成 1已完成
     */
    private Integer status;

    /**
     * 最终填表人
     */
    private Integer finalFillFormBy;

    /**
     * 下发人 医生编号
     */
    private String doctorId;

    /**
     * 下发人 领导编号
     */
    private String leaderId;

    /**
     * 创建时间
     */
    private String createDt;

    /**
     * 填写时间
     */
    private String fillDt;

    /**
     * 入库时间
     */
    private String insertDt;

    /**
     * 更新时间
     */
    private String modifyDt;

    /**
     * 是否有效数据 1有效 0无效
     */
    private Integer isValid;

    /**
     * 随访内容外建
     */
    private String foreignId;
    /**
     * 患者编号
     */
    private String memberId;
    /**
     * 随访教育者
     */
    private String doctorName;

    /**
     * 订单号
     */
    private String orderId;
    /**
     * 套餐名称
     */
    private String packageName;
    /**
     * 购买日期
     */
    private String buyDt;
    /**
     * 患者名称
     */
    private String memberName;
    /**
     * 联系方式
     */
    private String telephone;
    /**
     * 随访名称
     */
    private String followName;
    /**
     * 自定义随访模板id
     */
    private String templateId;
    
    /**
     * 江苏南京添加小程序健康评估提交多个医生 - 20191107
     */
    private String doctorIds;
    private String hospitalId;

    public String getTemplateId() {
        return templateId;
    }

    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    public String getFollowName() {
        return followName;
    }

    public void setFollowName(String followName) {
        this.followName = followName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.sid
     *
     * @return the value of t_main_follow.sid
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.sid
     *
     * @param sid the value for t_main_follow.sid
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.type
     *
     * @return the value of t_main_follow.type
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.type
     *
     * @param type the value for t_main_follow.type
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.next_dt
     *
     * @return the value of t_main_follow.next_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getNextDt() {
        return nextDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.next_dt
     *
     * @param nextDt the value for t_main_follow.next_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setNextDt(String nextDt) {
        this.nextDt = nextDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.fill_form_by
     *
     * @return the value of t_main_follow.fill_form_by
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public Integer getFillFormBy() {
        return fillFormBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.fill_form_by
     *
     * @param fillFormBy the value for t_main_follow.fill_form_by
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setFillFormBy(Integer fillFormBy) {
        this.fillFormBy = fillFormBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.status
     *
     * @return the value of t_main_follow.status
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.status
     *
     * @param status the value for t_main_follow.status
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.final_fill_form_by
     *
     * @return the value of t_main_follow.final_fill_form_by
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public Integer getFinalFillFormBy() {
        return finalFillFormBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.final_fill_form_by
     *
     * @param finalFillFormBy the value for t_main_follow.final_fill_form_by
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setFinalFillFormBy(Integer finalFillFormBy) {
        this.finalFillFormBy = finalFillFormBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.doctor_id
     *
     * @return the value of t_main_follow.doctor_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.doctor_id
     *
     * @param doctorId the value for t_main_follow.doctor_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.leader_id
     *
     * @return the value of t_main_follow.leader_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.leader_id
     *
     * @param leaderId the value for t_main_follow.leader_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.create_dt
     *
     * @return the value of t_main_follow.create_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.create_dt
     *
     * @param createDt the value for t_main_follow.create_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.fill_dt
     *
     * @return the value of t_main_follow.fill_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getFillDt() {
        return fillDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.fill_dt
     *
     * @param fillDt the value for t_main_follow.fill_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setFillDt(String fillDt) {
        this.fillDt = fillDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.insert_dt
     *
     * @return the value of t_main_follow.insert_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.insert_dt
     *
     * @param insertDt the value for t_main_follow.insert_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.modify_dt
     *
     * @return the value of t_main_follow.modify_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.modify_dt
     *
     * @param modifyDt the value for t_main_follow.modify_dt
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.is_valid
     *
     * @return the value of t_main_follow.is_valid
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.is_valid
     *
     * @param isValid the value for t_main_follow.is_valid
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.foreign_id
     *
     * @return the value of t_main_follow.foreign_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getForeignId() {
        return foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.foreign_id
     *
     * @param foreignId the value for t_main_follow.foreign_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setForeignId(String foreignId) {
        this.foreignId = foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_main_follow.member_id
     *
     * @return the value of t_main_follow.member_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_main_follow.member_id
     *
     * @param memberId the value for t_main_follow.member_id
     *
     * @mbggenerated Tue Mar 27 09:38:18 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * 随访者名称
     * @param doctorName
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    /**
     * 随访者名称
     */
    public String getDoctorName() {
        return doctorName;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getBuyDt() {
        return buyDt;
    }

    public void setBuyDt(String buyDt) {
        this.buyDt = buyDt;
    }

    public String getMemberName() {
        return memberName;
    }

    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Integer getFollowType() {
        return followType;
    }

    public void setFollowType(Integer followType) {
        this.followType = followType;
    }

	public String getDoctorIds() {
		return doctorIds;
	}

	public void setDoctorIds(String doctorIds) {
		this.doctorIds = doctorIds;
	}

    public String getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }
}