package com.comvee.cdms.follow.po;


import java.io.Serializable;
/**
 * 
 * @author 李左河
 *
 */
public class MemberFollowSetPO implements Serializable {

    private String sid;

    /**
     * 随访对象，患者编号
     */
    private String memberId;

    /**
     * 随访负责工作室，工作室领导（首席）编号
     */
    private String leaderId;

    /**
     * 最后一个创建/修改的医生编号
     */
    private String doctorId;

    /**
     * 添加时间
     */
    private String insertDt;

    /**
     * 更新时间
     */
    private String modifyDt;

    /**
     * 是否有效 1有 0否
     */
    private Integer isValid;

    /**
     * 随访循环周期 1:一个月(30天)，2:两个月(60天) 3:三个月(90天) 4:半年(120天)
     */
    private Integer cycleDt;

    /**
     * 下一次随访时间
     */
    private String nextDt;

    /**
     * 最近一次随访时间
     */
    private String lastDt;

    /**
     * 最近一次随访编号
     */
    private String lastFollowId;

    /**
     * 随访类型 1出院定期随访
     */
    private Integer followType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.sid
     *
     * @return the value of t_member_follow_set.sid
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.sid
     *
     * @param sid the value for t_member_follow_set.sid
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.member_id
     *
     * @return the value of t_member_follow_set.member_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.member_id
     *
     * @param memberId the value for t_member_follow_set.member_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.leader_id
     *
     * @return the value of t_member_follow_set.leader_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.leader_id
     *
     * @param leaderId the value for t_member_follow_set.leader_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.doctor_id
     *
     * @return the value of t_member_follow_set.doctor_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.doctor_id
     *
     * @param doctorId the value for t_member_follow_set.doctor_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.insert_dt
     *
     * @return the value of t_member_follow_set.insert_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.insert_dt
     *
     * @param insertDt the value for t_member_follow_set.insert_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.modify_dt
     *
     * @return the value of t_member_follow_set.modify_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.modify_dt
     *
     * @param modifyDt the value for t_member_follow_set.modify_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.is_valid
     *
     * @return the value of t_member_follow_set.is_valid
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.is_valid
     *
     * @param isValid the value for t_member_follow_set.is_valid
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.cycle_dt
     *
     * @return the value of t_member_follow_set.cycle_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public Integer getCycleDt() {
        return cycleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.cycle_dt
     *
     * @param cycleDt the value for t_member_follow_set.cycle_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setCycleDt(Integer cycleDt) {
        this.cycleDt = cycleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.next_dt
     *
     * @return the value of t_member_follow_set.next_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getNextDt() {
        return nextDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.next_dt
     *
     * @param nextDt the value for t_member_follow_set.next_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setNextDt(String nextDt) {
        this.nextDt = nextDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.last_dt
     *
     * @return the value of t_member_follow_set.last_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getLastDt() {
        return lastDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.last_dt
     *
     * @param lastDt the value for t_member_follow_set.last_dt
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setLastDt(String lastDt) {
        this.lastDt = lastDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.last_follow_id
     *
     * @return the value of t_member_follow_set.last_follow_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public String getLastFollowId() {
        return lastFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.last_follow_id
     *
     * @param lastFollowId the value for t_member_follow_set.last_follow_id
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setLastFollowId(String lastFollowId) {
        this.lastFollowId = lastFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_follow_set.follow_type
     *
     * @return the value of t_member_follow_set.follow_type
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public Integer getFollowType() {
        return followType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_follow_set.follow_type
     *
     * @param followType the value for t_member_follow_set.follow_type
     *
     * @mbggenerated Tue Feb 06 14:46:56 CST 2018
     */
    public void setFollowType(Integer followType) {
        this.followType = followType;
    }
}