package com.comvee.cdms.dialogue.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dialogue_group
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DialogueGroupPO {
    /**
     * sid
     */
    private String sid;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 发送者id
     * sender_id
     */
    private String senderId;

    /**
     * 消息类型 1 文本 2 图片 3 语音
     * msg_type
     */
    private Integer msgType;

    /**
     * 消息内容（json）
     * msg_content
     */
    private String msgContent;

    /**
     * 发送状态  1 未发送 2 已发送 3 发送失败
     * send_status
     */
    private Integer sendStatus;

    /**
     * 患者id数据，逗号隔开
     * member_id_data
     */
    private String memberIdData;

    /**
     * 患者姓名，json数组
     * member_name_json
     */
    private String memberNameJson;

    /**
     * 群发人数
     * people_number
     */
    private Integer peopleNumber;

    /**
     * 消息格式json
     * data_json
     */
    private String dataJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.sid
     *
     * @return the value of t_dialogue_group.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.sid
     *
     * @param sid the value for t_dialogue_group.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.insert_dt
     *
     * @return the value of t_dialogue_group.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.insert_dt
     *
     * @param insertDt the value for t_dialogue_group.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.update_dt
     *
     * @return the value of t_dialogue_group.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.update_dt
     *
     * @param updateDt the value for t_dialogue_group.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.doctor_id
     *
     * @return the value of t_dialogue_group.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.doctor_id
     *
     * @param doctorId the value for t_dialogue_group.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.sender_id
     *
     * @return the value of t_dialogue_group.sender_id
     *
     * @mbggenerated
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.sender_id
     *
     * @param senderId the value for t_dialogue_group.sender_id
     *
     * @mbggenerated
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.msg_type
     *
     * @return the value of t_dialogue_group.msg_type
     *
     * @mbggenerated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.msg_type
     *
     * @param msgType the value for t_dialogue_group.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.msg_content
     *
     * @return the value of t_dialogue_group.msg_content
     *
     * @mbggenerated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.msg_content
     *
     * @param msgContent the value for t_dialogue_group.msg_content
     *
     * @mbggenerated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.send_status
     *
     * @return the value of t_dialogue_group.send_status
     *
     * @mbggenerated
     */
    public Integer getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.send_status
     *
     * @param sendStatus the value for t_dialogue_group.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.member_id_data
     *
     * @return the value of t_dialogue_group.member_id_data
     *
     * @mbggenerated
     */
    public String getMemberIdData() {
        return memberIdData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.member_id_data
     *
     * @param memberIdData the value for t_dialogue_group.member_id_data
     *
     * @mbggenerated
     */
    public void setMemberIdData(String memberIdData) {
        this.memberIdData = memberIdData == null ? null : memberIdData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.member_name_json
     *
     * @return the value of t_dialogue_group.member_name_json
     *
     * @mbggenerated
     */
    public String getMemberNameJson() {
        return memberNameJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.member_name_json
     *
     * @param memberNameJson the value for t_dialogue_group.member_name_json
     *
     * @mbggenerated
     */
    public void setMemberNameJson(String memberNameJson) {
        this.memberNameJson = memberNameJson == null ? null : memberNameJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.people_number
     *
     * @return the value of t_dialogue_group.people_number
     *
     * @mbggenerated
     */
    public Integer getPeopleNumber() {
        return peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.people_number
     *
     * @param peopleNumber the value for t_dialogue_group.people_number
     *
     * @mbggenerated
     */
    public void setPeopleNumber(Integer peopleNumber) {
        this.peopleNumber = peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dialogue_group.data_json
     *
     * @return the value of t_dialogue_group.data_json
     *
     * @mbggenerated
     */
    public String getDataJson() {
        return dataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dialogue_group.data_json
     *
     * @param dataJson the value for t_dialogue_group.data_json
     *
     * @mbggenerated
     */
    public void setDataJson(String dataJson) {
        this.dataJson = dataJson == null ? null : dataJson.trim();
    }
}