package com.comvee.cdms.hospital.model.dto;

import javax.validation.constraints.NotEmpty;

import javax.validation.constraints.NotNull;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hospital
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddHospitalDTO {


    /**
     * 医院名称
     * hospital_name
     */
    @NotEmpty
    private String hospitalName;

    /**
     * 医院类型
     * hospital_type
     */
    @NotNull
    private Integer hospitalType;

    /**
     * 类型名称
     * type_name
     */
    @NotEmpty
    private String typeName;

    /**
     * 医院性质
     * hospital_nature
     */
    @NotNull
    private Integer hospitalNature;

    /**
     * 性质名称
     * nature_name
     */
    @NotEmpty
    private String natureName;

    /**
     * 省份id
     * province_id
     */
    @NotEmpty
    private String provinceId;

    /**
     * 省份名称
     * province_name
     */
    @NotEmpty
    private String provinceName;

    /**
     * 城市id
     * city_id
     */
    @NotEmpty
    private String cityId;

    /**
     * 城市名
     * city_name
     */
    @NotEmpty
    private String cityName;

    /**
     * 区域id
     * area_id
     */

    private String areaId;

    /**
     * 区域名称
     * area_name
     */

    private String areaName;

    /**
     * 医院等级  1 社区 2 街道  3 乡镇 4 县级 5市级
     */
    private Integer level;

    /**
     * 上级医院id ','隔开
     */
    private String upHospitalId;

    /**
     * 下级医院id ','隔开
     */
    private String downHospitalId;

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public Integer getHospitalType() {
        return hospitalType;
    }

    public void setHospitalType(Integer hospitalType) {
        this.hospitalType = hospitalType;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Integer getHospitalNature() {
        return hospitalNature;
    }

    public void setHospitalNature(Integer hospitalNature) {
        this.hospitalNature = hospitalNature;
    }

    public String getNatureName() {
        return natureName;
    }

    public void setNatureName(String natureName) {
        this.natureName = natureName;
    }

    public String getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getUpHospitalId() {
        return upHospitalId;
    }

    public void setUpHospitalId(String upHospitalId) {
        this.upHospitalId = upHospitalId;
    }

    public String getDownHospitalId() {
        return downHospitalId;
    }

    public void setDownHospitalId(String downHospitalId) {
        this.downHospitalId = downHospitalId;
    }
}