package com.comvee.cdms.sign.mapper;

import com.comvee.cdms.sign.po.WhrPO;
import com.comvee.cdms.sign.po.WhrPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WhrPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int countByExample(WhrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int deleteByExample(WhrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int insert(WhrPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int insertSelective(WhrPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    List<WhrPO> selectByExample(WhrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    WhrPO selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") WhrPO record, @Param("example") WhrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int updateByExample(@Param("record") WhrPO record, @Param("example") WhrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int updateByPrimaryKeySelective(WhrPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    int updateByPrimaryKey(WhrPO record);

    /**
     * 获取患者最新的腰臀比记录
     * v5.0.0
     * @param memberId
     * @return
     */
    WhrPO getNewWhr(@Param("memberId") String memberId);
}