package com.comvee.cdms.member.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_member
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DoctorMemberPO {
    /**
     * 主键
     * sid
     */
    private String sid;

    /**
     * 患者编号
     * member_id
     */
    private String memberId;

    /**
     * 医生编号
     * doctor_id
     */
    private String doctorId;

    /**
     * 插入时间
     * insert_dt
     */
    private String insertDt;

    /**
     * 更新时间
     * modify_time_stamp
     */
    private String modifyTimeStamp;

    /**
     * 是否有效 1有效 0无效
     * is_valid
     */
    private Integer isValid;

    /**
     * 是否是患者的主治医生 1是 0否
     * is_attend
     */
    private Integer isAttend;

    /**
     * 标签
     * label
     */
    private String label;

    /**
     * 0：默认分组，非0为真实分组
     * group_id
     */
    private String groupId;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 关注状态 1 已关注 0 未关注
     * concern_status
     */
    private Integer concernStatus;

    private String priceFlag;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.sid
     *
     * @return the value of t_doctor_member.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.sid
     *
     * @param sid the value for t_doctor_member.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.member_id
     *
     * @return the value of t_doctor_member.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.member_id
     *
     * @param memberId the value for t_doctor_member.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.doctor_id
     *
     * @return the value of t_doctor_member.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.doctor_id
     *
     * @param doctorId the value for t_doctor_member.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.insert_dt
     *
     * @return the value of t_doctor_member.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.insert_dt
     *
     * @param insertDt the value for t_doctor_member.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.modify_time_stamp
     *
     * @return the value of t_doctor_member.modify_time_stamp
     *
     * @mbggenerated
     */
    public String getModifyTimeStamp() {
        return modifyTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.modify_time_stamp
     *
     * @param modifyTimeStamp the value for t_doctor_member.modify_time_stamp
     *
     * @mbggenerated
     */
    public void setModifyTimeStamp(String modifyTimeStamp) {
        this.modifyTimeStamp = modifyTimeStamp == null ? null : modifyTimeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.is_valid
     *
     * @return the value of t_doctor_member.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.is_valid
     *
     * @param isValid the value for t_doctor_member.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.is_attend
     *
     * @return the value of t_doctor_member.is_attend
     *
     * @mbggenerated
     */
    public Integer getIsAttend() {
        return isAttend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.is_attend
     *
     * @param isAttend the value for t_doctor_member.is_attend
     *
     * @mbggenerated
     */
    public void setIsAttend(Integer isAttend) {
        this.isAttend = isAttend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.label
     *
     * @return the value of t_doctor_member.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.label
     *
     * @param label the value for t_doctor_member.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.group_id
     *
     * @return the value of t_doctor_member.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.group_id
     *
     * @param groupId the value for t_doctor_member.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.operator_id
     *
     * @return the value of t_doctor_member.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.operator_id
     *
     * @param operatorId the value for t_doctor_member.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_member.concern_status
     *
     * @return the value of t_doctor_member.concern_status
     *
     * @mbggenerated
     */
    public Integer getConcernStatus() {
        return concernStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_member.concern_status
     *
     * @param concernStatus the value for t_doctor_member.concern_status
     *
     * @mbggenerated
     */
    public void setConcernStatus(Integer concernStatus) {
        this.concernStatus = concernStatus;
    }

    public String getPriceFlag() {
        return priceFlag;
    }

    public void setPriceFlag(String priceFlag) {
        this.priceFlag = priceFlag;
    }
}