package com.comvee.cdms.member.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_member_join_hospital
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class MemberJoinHospitalPO {
    /**
     * sid
     */
    private String sid;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医院id
     * hospital_id
     */
    private String hospitalId;

    /**
     * 加入类型
     * join_type
     */
    private Integer joinType;

    /**
     * 业务id
     * foreign_id
     */
    private String foreignId;

    /**
     * 操作者类型
     * operator_type
     */
    private Integer operatorType;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 加入时间
     * in_date
     */
    private String inDate;

    /**
     * 扩展数据json
     * ext_data
     */
    private String extData;

    private Integer attention;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.sid
     *
     * @return the value of t_member_join_hospital.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.sid
     *
     * @param sid the value for t_member_join_hospital.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.member_id
     *
     * @return the value of t_member_join_hospital.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.member_id
     *
     * @param memberId the value for t_member_join_hospital.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.hospital_id
     *
     * @return the value of t_member_join_hospital.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.hospital_id
     *
     * @param hospitalId the value for t_member_join_hospital.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.join_type
     *
     * @return the value of t_member_join_hospital.join_type
     *
     * @mbggenerated
     */
    public Integer getJoinType() {
        return joinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.join_type
     *
     * @param joinType the value for t_member_join_hospital.join_type
     *
     * @mbggenerated
     */
    public void setJoinType(Integer joinType) {
        this.joinType = joinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.foreign_id
     *
     * @return the value of t_member_join_hospital.foreign_id
     *
     * @mbggenerated
     */
    public String getForeignId() {
        return foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.foreign_id
     *
     * @param foreignId the value for t_member_join_hospital.foreign_id
     *
     * @mbggenerated
     */
    public void setForeignId(String foreignId) {
        this.foreignId = foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.operator_type
     *
     * @return the value of t_member_join_hospital.operator_type
     *
     * @mbggenerated
     */
    public Integer getoperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.operator_type
     *
     * @param operatorType the value for t_member_join_hospital.operator_type
     *
     * @mbggenerated
     */
    public void setoperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.operator_id
     *
     * @return the value of t_member_join_hospital.operator_id
     *
     * @mbggenerated
     */
    public String getoperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.operator_id
     *
     * @param operatorId the value for t_member_join_hospital.operator_id
     *
     * @mbggenerated
     */
    public void setoperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.in_date
     *
     * @return the value of t_member_join_hospital.in_date
     *
     * @mbggenerated
     */
    public String getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.in_date
     *
     * @param inDate the value for t_member_join_hospital.in_date
     *
     * @mbggenerated
     */
    public void setInDate(String inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.ext_data
     *
     * @return the value of t_member_join_hospital.ext_data
     *
     * @mbggenerated
     */
    public String getExtData() {
        return extData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.ext_data
     *
     * @param extData the value for t_member_join_hospital.ext_data
     *
     * @mbggenerated
     */
    public void setExtData(String extData) {
        this.extData = extData;
    }


    public Integer getAttention() {
        return attention;
    }

    public void setAttention(Integer attention) {
        this.attention = attention;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.insert_dt
     *
     * @return the value of t_member_join_hospital.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.insert_dt
     *
     * @param insertDt the value for t_member_join_hospital.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.update_dt
     *
     * @return the value of t_member_join_hospital.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.update_dt
     *
     * @param updateDt the value for t_member_join_hospital.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_join_hospital.valid
     *
     * @return the value of t_member_join_hospital.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_join_hospital.valid
     *
     * @param valid the value for t_member_join_hospital.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

}