package com.comvee.cdms.admin.model.vo;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_admin
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AdminVO {
    /**
     * admin_id
     */
    private String adminId;

    /**
     * 管理员名称
     * admin_name
     */
    private String adminName;

    /**
     * 账号
     * account_no
     */
    private String accountNo;

    /**
     * 最后一次登录时间
     * last_login_dt
     */
    private String lastLoginDt;

    /**
     * 状态 1 正常 2 禁用
     * account_status
     */
    private Integer accountStatus;

    /**
     * 登录ip
     */
    private String lastLoginIp;

    public String getAdminId() {
        return adminId;
    }

    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getAccountNo() {
        return accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    public String getLastLoginDt() {
        return lastLoginDt;
    }

    public void setLastLoginDt(String lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    public Integer getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    public String getLastLoginIp() {
        return lastLoginIp;
    }

    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }
}