package com.comvee.cdms.dybloodsugar.mapper;

import com.comvee.cdms.dybloodsugar.dto.MemberSensorShowDTO;
import com.comvee.cdms.dybloodsugar.po.DYMemberSensorShowPO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DYMemberSensorShowPOMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    int insert(DYMemberSensorShowPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    int insertSelective(DYMemberSensorShowPO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    DYMemberSensorShowPO selectByPrimaryKey(Long sid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DYMemberSensorShowPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_member_sensor_show
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DYMemberSensorShowPO record);

    List<DYMemberSensorShowPO> listMemberSensorShow(MemberSensorShowDTO dto);

    void deleteById(String sid);

    void deleteByDTO(MemberSensorShowDTO dto);
}