package com.comvee.cdms.other.bo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_push_token
 *
 * @mbggenerated do_not_delete_during_merge
 * @author Su
 */
public class DoctorPushTokenBO {



    /**
     * doctor_id
     */
    private String doctorId;


    /**
     * push_token
     */
    private String pushToken;

    /**
     * 设备类型 1 安卓 2 ios
     * device_type
     */
    private Integer deviceType;

    /**
     * 渠道code
     * channel_code
     */
    private String channelCode;

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public String getPushToken() {
        return pushToken;
    }

    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    public Integer getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    public String getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }
}