package com.comvee.cdms.packages.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_member_package
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddMemberPackageMapperDTO {
    /**
     * sid
     */
    private String sid;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 套餐id
     * package_id
     */
    private String packageId;

    /**
     * 订单id
     * order_id
     */
    private String orderId;

    /**
     * 开始时间
     * start_dt
     */
    private String startDt;

    /**
     * 结束时间
     * end_dt
     */
    private String endDt;



    /**
     * 套餐名称
     * package_name
     */
    private String packageName;

    /**
     * 价格（分）
     * price
     */
    private String price;

    /**
     * 套餐状态  1 ：正常 2 ： 退订
     * package_status
     */
    private Integer packageStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.sid
     *
     * @return the value of t_member_package.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.sid
     *
     * @param sid the value for t_member_package.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.member_id
     *
     * @return the value of t_member_package.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.member_id
     *
     * @param memberId the value for t_member_package.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.doctor_id
     *
     * @return the value of t_member_package.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.doctor_id
     *
     * @param doctorId the value for t_member_package.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.package_id
     *
     * @return the value of t_member_package.package_id
     *
     * @mbggenerated
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.package_id
     *
     * @param packageId the value for t_member_package.package_id
     *
     * @mbggenerated
     */
    public void setPackageId(String packageId) {
        this.packageId = packageId == null ? null : packageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.order_id
     *
     * @return the value of t_member_package.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.order_id
     *
     * @param orderId the value for t_member_package.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.start_dt
     *
     * @return the value of t_member_package.start_dt
     *
     * @mbggenerated
     */
    public String getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.start_dt
     *
     * @param startDt the value for t_member_package.start_dt
     *
     * @mbggenerated
     */
    public void setStartDt(String startDt) {
        this.startDt = startDt == null ? null : startDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.end_dt
     *
     * @return the value of t_member_package.end_dt
     *
     * @mbggenerated
     */
    public String getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.end_dt
     *
     * @param endDt the value for t_member_package.end_dt
     *
     * @mbggenerated
     */
    public void setEndDt(String endDt) {
        this.endDt = endDt == null ? null : endDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.package_name
     *
     * @return the value of t_member_package.package_name
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.package_name
     *
     * @param packageName the value for t_member_package.package_name
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.price
     *
     * @return the value of t_member_package.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.price
     *
     * @param price the value for t_member_package.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_package.package_status
     *
     * @return the value of t_member_package.package_status
     *
     * @mbggenerated
     */
    public Integer getPackageStatus() {
        return packageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_package.package_status
     *
     * @param packageStatus the value for t_member_package.package_status
     *
     * @mbggenerated
     */
    public void setPackageStatus(Integer packageStatus) {
        this.packageStatus = packageStatus;
    }
}