package com.comvee.cdms.sign.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_blood_pressure
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class BloodPressurePO {
    /**
     * sid
     */
    private String sid;

    /**
     * 舒张压
     * dbp
     */
    private String dbp;

    /**
     * 收缩压
     * sbp
     */
    private String sbp;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 记录时间
     * record_time
     */
    private String recordTime;

    /**
     * 收缩压级别（1：低 3:正常 5：偏高）
     * sbp_level
     */
    private Integer sbpLevel;

    /**
     * 舒张压级别（1 偏低  3正常 5偏高）
     * dbp_level
     */
    private Integer dbpLevel;

    /**
     * 入库时间
     * insert_dt
     */
    private String insertDt;

    /**
     * 是否有效
     * is_valid
     */
    private Integer isValid;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 操作者类型 1 用户 2 医护
     * operator_type
     */
    private Integer operatorType;

    /**
     * operator_id
     */
    private String operatorId;

    /**
     * 来源
     * origin
     */
    private Integer origin;

    private String dbpMin;
    private String dbpMax;

    private String sbpMin;
    private String sbpMax;

    private String heartRate;//心率


    public String getDbpMin() {
        return dbpMin;
    }

    public void setDbpMin(String dbpMin) {
        this.dbpMin = dbpMin;
    }

    public String getDbpMax() {
        return dbpMax;
    }

    public void setDbpMax(String dbpMax) {
        this.dbpMax = dbpMax;
    }

    public String getSbpMin() {
        return sbpMin;
    }

    public void setSbpMin(String sbpMin) {
        this.sbpMin = sbpMin;
    }

    public String getSbpMax() {
        return sbpMax;
    }

    public void setSbpMax(String sbpMax) {
        this.sbpMax = sbpMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.sid
     *
     * @return the value of t_blood_pressure.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.sid
     *
     * @param sid the value for t_blood_pressure.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.dbp
     *
     * @return the value of t_blood_pressure.dbp
     *
     * @mbggenerated
     */
    public String getDbp() {
        return dbp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.dbp
     *
     * @param dbp the value for t_blood_pressure.dbp
     *
     * @mbggenerated
     */
    public void setDbp(String dbp) {
        this.dbp = dbp == null ? null : dbp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.sbp
     *
     * @return the value of t_blood_pressure.sbp
     *
     * @mbggenerated
     */
    public String getSbp() {
        return sbp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.sbp
     *
     * @param sbp the value for t_blood_pressure.sbp
     *
     * @mbggenerated
     */
    public void setSbp(String sbp) {
        this.sbp = sbp == null ? null : sbp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.member_id
     *
     * @return the value of t_blood_pressure.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.member_id
     *
     * @param memberId the value for t_blood_pressure.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.record_time
     *
     * @return the value of t_blood_pressure.record_time
     *
     * @mbggenerated
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.record_time
     *
     * @param recordTime the value for t_blood_pressure.record_time
     *
     * @mbggenerated
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime == null ? null : recordTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.sbp_level
     *
     * @return the value of t_blood_pressure.sbp_level
     *
     * @mbggenerated
     */
    public Integer getSbpLevel() {
        return sbpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.sbp_level
     *
     * @param sbpLevel the value for t_blood_pressure.sbp_level
     *
     * @mbggenerated
     */
    public void setSbpLevel(Integer sbpLevel) {
        this.sbpLevel = sbpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.dbp_level
     *
     * @return the value of t_blood_pressure.dbp_level
     *
     * @mbggenerated
     */
    public Integer getDbpLevel() {
        return dbpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.dbp_level
     *
     * @param dbpLevel the value for t_blood_pressure.dbp_level
     *
     * @mbggenerated
     */
    public void setDbpLevel(Integer dbpLevel) {
        this.dbpLevel = dbpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.insert_dt
     *
     * @return the value of t_blood_pressure.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.insert_dt
     *
     * @param insertDt the value for t_blood_pressure.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.is_valid
     *
     * @return the value of t_blood_pressure.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.is_valid
     *
     * @param isValid the value for t_blood_pressure.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.update_dt
     *
     * @return the value of t_blood_pressure.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.update_dt
     *
     * @param updateDt the value for t_blood_pressure.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.operator_type
     *
     * @return the value of t_blood_pressure.operator_type
     *
     * @mbggenerated
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.operator_type
     *
     * @param operatorType the value for t_blood_pressure.operator_type
     *
     * @mbggenerated
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.operator_id
     *
     * @return the value of t_blood_pressure.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.operator_id
     *
     * @param operatorId the value for t_blood_pressure.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure.origin
     *
     * @return the value of t_blood_pressure.origin
     *
     * @mbggenerated
     */
    public Integer getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure.origin
     *
     * @param origin the value for t_blood_pressure.origin
     *
     * @mbggenerated
     */
    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    public String getHeartRate() {
        return heartRate;
    }

    public void setHeartRate(String heartRate) {
        this.heartRate = heartRate;
    }
}