package com.comvee.cdms.sign.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hba1c
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Hba1cPO {
    /**
     * sid
     */
    private String sid;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 记录的值
     * record_value
     */
    private Float recordValue;

    /**
     * 记录值等级 3 正常 5 偏高
     * record_level
     */
    private Integer recordLevel;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 操作类型 1 患者 2 医生
     * operator_type
     */
    private Integer operatorType;

    /**
     * 记录日期
     * record_dt
     */
    private String recordDt;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 备注
     * remark
     */
    private String remark;

    /**
     * valid
     */
    private Integer valid;

    /**
     * 参数范围最大值
     * range_max
     */
    private String rangeMax;

    /**
     * 来源1小程序 2web 3医生端
     */
    private Integer origin;

    public Integer getOrigin() {
        return origin;
    }

    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.sid
     *
     * @return the value of t_hba1c.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.sid
     *
     * @param sid the value for t_hba1c.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.member_id
     *
     * @return the value of t_hba1c.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.member_id
     *
     * @param memberId the value for t_hba1c.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.record_value
     *
     * @return the value of t_hba1c.record_value
     *
     * @mbggenerated
     */
    public Float getRecordValue() {
        return recordValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.record_value
     *
     * @param recordValue the value for t_hba1c.record_value
     *
     * @mbggenerated
     */
    public void setRecordValue(Float recordValue) {
        this.recordValue = recordValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.record_level
     *
     * @return the value of t_hba1c.record_level
     *
     * @mbggenerated
     */
    public Integer getRecordLevel() {
        return recordLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.record_level
     *
     * @param recordLevel the value for t_hba1c.record_level
     *
     * @mbggenerated
     */
    public void setRecordLevel(Integer recordLevel) {
        this.recordLevel = recordLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.operator_id
     *
     * @return the value of t_hba1c.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.operator_id
     *
     * @param operatorId the value for t_hba1c.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.operator_type
     *
     * @return the value of t_hba1c.operator_type
     *
     * @mbggenerated
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.operator_type
     *
     * @param operatorType the value for t_hba1c.operator_type
     *
     * @mbggenerated
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.record_dt
     *
     * @return the value of t_hba1c.record_dt
     *
     * @mbggenerated
     */
    public String getRecordDt() {
        return recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.record_dt
     *
     * @param recordDt the value for t_hba1c.record_dt
     *
     * @mbggenerated
     */
    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.insert_dt
     *
     * @return the value of t_hba1c.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.insert_dt
     *
     * @param insertDt the value for t_hba1c.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.update_dt
     *
     * @return the value of t_hba1c.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.update_dt
     *
     * @param updateDt the value for t_hba1c.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.remark
     *
     * @return the value of t_hba1c.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.remark
     *
     * @param remark the value for t_hba1c.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.valid
     *
     * @return the value of t_hba1c.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.valid
     *
     * @param valid the value for t_hba1c.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hba1c.range_max
     *
     * @return the value of t_hba1c.range_max
     *
     * @mbggenerated
     */
    public String getRangeMax() {
        return rangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hba1c.range_max
     *
     * @param rangeMax the value for t_hba1c.range_max
     *
     * @mbggenerated
     */
    public void setRangeMax(String rangeMax) {
        this.rangeMax = rangeMax;
    }
}