package com.comvee.cdms.sign.po;

public class WhrPO {
    private String sid;

    /**
     * 腰围
     */
    private String waist;

    /**
     * 臀围
     */
    private String hip;

    /**
     * 腰臀比
     */
    private String whr;

    /**
     * 记录时间
     */
    private String recordDt;

    /**
     * 入库时间
     */
    private String insertDt;

    /**
     * 患者编号
     */
    private String memberId;

    /**
     * 是否有效 1有 0否
     */
    private Integer isValid;

    /**
     * 来源 1小程序 2web 3医生端
     */
    private Integer origin;

    /**
     * 更新时间
     */
    private String updateDt;

    /**
     * 操作者类型 1 用户 2 医护
     */
    private Integer operatorType;

    /**
     * 操作者编号
     */
    private String operatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.sid
     *
     * @return the value of t_whr.sid
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.sid
     *
     * @param sid the value for t_whr.sid
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.waist
     *
     * @return the value of t_whr.waist
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getWaist() {
        return waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.waist
     *
     * @param waist the value for t_whr.waist
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setWaist(String waist) {
        this.waist = waist == null ? null : waist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.hip
     *
     * @return the value of t_whr.hip
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getHip() {
        return hip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.hip
     *
     * @param hip the value for t_whr.hip
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setHip(String hip) {
        this.hip = hip == null ? null : hip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.whr
     *
     * @return the value of t_whr.whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getWhr() {
        return whr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.whr
     *
     * @param whr the value for t_whr.whr
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setWhr(String whr) {
        this.whr = whr == null ? null : whr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.record_dt
     *
     * @return the value of t_whr.record_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getRecordDt() {
        return recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.record_dt
     *
     * @param recordDt the value for t_whr.record_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.insert_dt
     *
     * @return the value of t_whr.insert_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.insert_dt
     *
     * @param insertDt the value for t_whr.insert_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.member_id
     *
     * @return the value of t_whr.member_id
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.member_id
     *
     * @param memberId the value for t_whr.member_id
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.is_valid
     *
     * @return the value of t_whr.is_valid
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.is_valid
     *
     * @param isValid the value for t_whr.is_valid
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.origin
     *
     * @return the value of t_whr.origin
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public Integer getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.origin
     *
     * @param origin the value for t_whr.origin
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.update_dt
     *
     * @return the value of t_whr.update_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.update_dt
     *
     * @param updateDt the value for t_whr.update_dt
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.operator_type
     *
     * @return the value of t_whr.operator_type
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.operator_type
     *
     * @param operatorType the value for t_whr.operator_type
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_whr.operator_id
     *
     * @return the value of t_whr.operator_id
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_whr.operator_id
     *
     * @param operatorId the value for t_whr.operator_id
     *
     * @mbggenerated Thu Sep 12 14:39:01 CST 2019
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }
}