package com.comvee.cdms.user.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_login_log
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class LoginLogPO {
    /**
     * log_id
     */
    private String logId;

    /**
     * 账号
     * user_name
     */
    private String userName;

    /**
     * 账号类型 1 web账号 2 后台账号
     * user_type
     */
    private Integer userType;

    /**
     *  登录日志
     * login_dt
     */
    private String loginDt;

    /**
     * 登陆ip
     * login_ip
     */
    private String loginIp;

    /**
     * 登录结果 1 成功  2 账号不存在 3 密码错误 4 账号被禁 5 其他
     * login_result
     */
    private Integer loginResult;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.log_id
     *
     * @return the value of t_login_log.log_id
     *
     * @mbggenerated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.log_id
     *
     * @param logId the value for t_login_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.user_name
     *
     * @return the value of t_login_log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.user_name
     *
     * @param userName the value for t_login_log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.user_type
     *
     * @return the value of t_login_log.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.user_type
     *
     * @param userType the value for t_login_log.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_dt
     *
     * @return the value of t_login_log.login_dt
     *
     * @mbggenerated
     */
    public String getLoginDt() {
        return loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_dt
     *
     * @param loginDt the value for t_login_log.login_dt
     *
     * @mbggenerated
     */
    public void setLoginDt(String loginDt) {
        this.loginDt = loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_ip
     *
     * @return the value of t_login_log.login_ip
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_ip
     *
     * @param loginIp the value for t_login_log.login_ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_result
     *
     * @return the value of t_login_log.login_result
     *
     * @mbggenerated
     */
    public Integer getLoginResult() {
        return loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_result
     *
     * @param loginResult the value for t_login_log.login_result
     *
     * @mbggenerated
     */
    public void setLoginResult(Integer loginResult) {
        this.loginResult = loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.insert_dt
     *
     * @return the value of t_login_log.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.insert_dt
     *
     * @param insertDt the value for t_login_log.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }
}