package com.comvee.cdms.foot.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_foot_report
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class FootReportPO {
    /**
     * sid
     */
    private String sid;

    /**
     * prescript_id
     */
    private String prescriptId;

    /**
     * report_id
     */
    private String reportId;

    /**
     * report_type
     */
    private Integer reportType;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    private Integer valid;

    public Integer getValid() {
        return valid;
    }

    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.sid
     *
     * @return the value of t_foot_report.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.sid
     *
     * @param sid the value for t_foot_report.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.prescript_id
     *
     * @return the value of t_foot_report.prescript_id
     *
     * @mbggenerated
     */
    public String getPrescriptId() {
        return prescriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.prescript_id
     *
     * @param prescriptId the value for t_foot_report.prescript_id
     *
     * @mbggenerated
     */
    public void setPrescriptId(String prescriptId) {
        this.prescriptId = prescriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.report_id
     *
     * @return the value of t_foot_report.report_id
     *
     * @mbggenerated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.report_id
     *
     * @param reportId the value for t_foot_report.report_id
     *
     * @mbggenerated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.report_type
     *
     * @return the value of t_foot_report.report_type
     *
     * @mbggenerated
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.report_type
     *
     * @param reportType the value for t_foot_report.report_type
     *
     * @mbggenerated
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.insert_dt
     *
     * @return the value of t_foot_report.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.insert_dt
     *
     * @param insertDt the value for t_foot_report.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_foot_report.update_dt
     *
     * @return the value of t_foot_report.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_foot_report.update_dt
     *
     * @param updateDt the value for t_foot_report.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }
}