package com.comvee.cdms.doctor.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_popup_remind_ignore_time
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DoctorPopupRemindIgnoreTimePO {
    /**
     * sid
     */
    private String sid;

    /**
     * doctor_id
     */
    private String doctorId;

    /**
     * remind_type
     */
    private Integer remindType;

    /**
     * 忽略时间
     * ignore_dt
     */
    private String ignoreDt;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.sid
     *
     * @return the value of t_doctor_popup_remind_ignore_time.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.sid
     *
     * @param sid the value for t_doctor_popup_remind_ignore_time.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.doctor_id
     *
     * @return the value of t_doctor_popup_remind_ignore_time.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.doctor_id
     *
     * @param doctorId the value for t_doctor_popup_remind_ignore_time.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.remind_type
     *
     * @return the value of t_doctor_popup_remind_ignore_time.remind_type
     *
     * @mbggenerated
     */
    public Integer getRemindType() {
        return remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.remind_type
     *
     * @param remindType the value for t_doctor_popup_remind_ignore_time.remind_type
     *
     * @mbggenerated
     */
    public void setRemindType(Integer remindType) {
        this.remindType = remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.ignore_dt
     *
     * @return the value of t_doctor_popup_remind_ignore_time.ignore_dt
     *
     * @mbggenerated
     */
    public String getIgnoreDt() {
        return ignoreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.ignore_dt
     *
     * @param ignoreDt the value for t_doctor_popup_remind_ignore_time.ignore_dt
     *
     * @mbggenerated
     */
    public void setIgnoreDt(String ignoreDt) {
        this.ignoreDt = ignoreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.insert_dt
     *
     * @return the value of t_doctor_popup_remind_ignore_time.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.insert_dt
     *
     * @param insertDt the value for t_doctor_popup_remind_ignore_time.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.update_dt
     *
     * @return the value of t_doctor_popup_remind_ignore_time.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.update_dt
     *
     * @param updateDt the value for t_doctor_popup_remind_ignore_time.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_popup_remind_ignore_time.valid
     *
     * @return the value of t_doctor_popup_remind_ignore_time.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_popup_remind_ignore_time.valid
     *
     * @param valid the value for t_doctor_popup_remind_ignore_time.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}