package com.comvee.cdms.doctor.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_service_time_set
 *
 * @mbggenerated do_not_delete_during_merge
 * @author Su
 */
public class DoctorServiceTimePO {
    /**
     * sid
     */
    private String sid;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 星期code
     * week_code
     */
    private String weekCode;

    /**
     * 开始时间
     * start_time
     */
    private String startTime;

    /**
     * 结束时间
     * end_time
     */
    private String endTime;

    /**
     * 启用状态 1 启用 0 关闭
     * open_status
     */
    private Integer openStatus;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.sid
     *
     * @return the value of t_doctor_service_time_set.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.sid
     *
     * @param sid the value for t_doctor_service_time_set.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.doctor_id
     *
     * @return the value of t_doctor_service_time_set.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.doctor_id
     *
     * @param doctorId the value for t_doctor_service_time_set.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.week_code
     *
     * @return the value of t_doctor_service_time_set.week_code
     *
     * @mbggenerated
     */
    public String getWeekCode() {
        return weekCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.week_code
     *
     * @param weekCode the value for t_doctor_service_time_set.week_code
     *
     * @mbggenerated
     */
    public void setWeekCode(String weekCode) {
        this.weekCode = weekCode == null ? null : weekCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.start_time
     *
     * @return the value of t_doctor_service_time_set.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.start_time
     *
     * @param startTime the value for t_doctor_service_time_set.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.end_time
     *
     * @return the value of t_doctor_service_time_set.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.end_time
     *
     * @param endTime the value for t_doctor_service_time_set.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.open_status
     *
     * @return the value of t_doctor_service_time_set.open_status
     *
     * @mbggenerated
     */
    public Integer getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.open_status
     *
     * @param openStatus the value for t_doctor_service_time_set.open_status
     *
     * @mbggenerated
     */
    public void setOpenStatus(Integer openStatus) {
        this.openStatus = openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.insert_dt
     *
     * @return the value of t_doctor_service_time_set.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.insert_dt
     *
     * @param insertDt the value for t_doctor_service_time_set.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_service_time_set.update_dt
     *
     * @return the value of t_doctor_service_time_set.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_service_time_set.update_dt
     *
     * @param updateDt the value for t_doctor_service_time_set.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}