package com.comvee.cdms.healthrecord.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_health_record_detail
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class HealthRecordDetailPO {
    /**
     * sid
     */
    private String sid;

    /**
     * t_health_record 表主键
     * pid
     */
    private String pid;

    /**
     * checkup_item
     */
    private String checkupItem;

    /**
     * checkup_result
     */
    private String checkupResult;

    /**
     * checkup_dt
     */
    private String checkupDt;

    /**
     * device_identifier
     */
    private String deviceIdentifier;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.sid
     *
     * @return the value of t_health_record_detail.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.sid
     *
     * @param sid the value for t_health_record_detail.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.pid
     *
     * @return the value of t_health_record_detail.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.pid
     *
     * @param pid the value for t_health_record_detail.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.checkup_item
     *
     * @return the value of t_health_record_detail.checkup_item
     *
     * @mbggenerated
     */
    public String getCheckupItem() {
        return checkupItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.checkup_item
     *
     * @param checkupItem the value for t_health_record_detail.checkup_item
     *
     * @mbggenerated
     */
    public void setCheckupItem(String checkupItem) {
        this.checkupItem = checkupItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.checkup_result
     *
     * @return the value of t_health_record_detail.checkup_result
     *
     * @mbggenerated
     */
    public String getCheckupResult() {
        return checkupResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.checkup_result
     *
     * @param checkupResult the value for t_health_record_detail.checkup_result
     *
     * @mbggenerated
     */
    public void setCheckupResult(String checkupResult) {
        this.checkupResult = checkupResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.checkup_dt
     *
     * @return the value of t_health_record_detail.checkup_dt
     *
     * @mbggenerated
     */
    public String getCheckupDt() {
        return checkupDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.checkup_dt
     *
     * @param checkupDt the value for t_health_record_detail.checkup_dt
     *
     * @mbggenerated
     */
    public void setCheckupDt(String checkupDt) {
        this.checkupDt = checkupDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.device_identifier
     *
     * @return the value of t_health_record_detail.device_identifier
     *
     * @mbggenerated
     */
    public String getDeviceIdentifier() {
        return deviceIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.device_identifier
     *
     * @param deviceIdentifier the value for t_health_record_detail.device_identifier
     *
     * @mbggenerated
     */
    public void setDeviceIdentifier(String deviceIdentifier) {
        this.deviceIdentifier = deviceIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.insert_dt
     *
     * @return the value of t_health_record_detail.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.insert_dt
     *
     * @param insertDt the value for t_health_record_detail.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.update_dt
     *
     * @return the value of t_health_record_detail.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.update_dt
     *
     * @param updateDt the value for t_health_record_detail.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_health_record_detail.valid
     *
     * @return the value of t_health_record_detail.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_health_record_detail.valid
     *
     * @param valid the value for t_health_record_detail.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}