package com.comvee.cdms.member.bo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_member_control_target
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class MemberControlTargetBO {


    /**
     * 空腹低
     * low_before_breakfast
     */
    private Float lowBeforeBreakfast;

    /**
     * 空腹高
     * high_before_breakfast
     */
    private Float highBeforeBreakfast;

    /**
     * 凌晨低
     * low_beforedawn
     */
    private Float lowBeforedawn;

    /**
     * 凌晨高
     * high_beforedawn
     */
    private Float highBeforedawn;


    /**
     * 餐后(两小时)低
     * low_after_meal
     */
    private Float lowAfterMeal;

    /**
     * 餐后(两小时)高
     * high_after_meal
     */
    private Float highAfterMeal;


    /**
     * 餐后(一小时)低
     * low_after_meal
     */
    private Float lowAfterMealOneHour;

    /**
     * 餐后(一小时)高
     * high_after_meal
     */
    private Float highAfterMealOneHour;
    /**
     * 睡前低
     * low_before_sleep
     */
    private Float lowBeforeSleep;

    /**
     * 睡前高
     * high_before_sleep
     */
    private Float highBeforeSleep;

    /**
     * 餐前低
     * low_before_meal
     */
    private Float lowBeforeMeal;

    /**
     * 餐前高
     * high_before_meal
     */
    private Float highBeforeMeal;

    /**
     * 收缩压上限
     * high_systolic_press
     */
    private Float highSystolicPress;

    /**
     * 收缩压下限
     * low_systolic_press
     */
    private Float lowSystolicPress;

    /**
     * 舒张压上限
     * high_diastolic_press
     */
    private Float highDiastolicPress;

    /**
     * 舒张压下限
     * low_diastolic_press
     */
    private Float lowDiastolicPress;

    /**
     * 糖化血红蛋白下限
     * low_glycosylated_val
     */
    private Float lowGlycosylatedVal;

    /**
     * 糖化血红蛋白上限
     * high_glycosylated_val
     */
    private Float highGlycosylatedVal;

    /**
     * 胆固醇下限
     * low_TCholesterol
     */
    private Float lowTCholesterol;

    /**
     * 胆固醇上限
     * high_TCholesterol
     */
    private Float highTCholesterol;

    /**
     * 甘油三酯下限
     * low_triglyceride
     */
    private Float lowTriglyceride;

    /**
     * 甘油三酯上限
     * high_triglyceride
     */
    private Float highTriglyceride;

    /**
     * 低密度脂蛋白下限
     * low_LDLCholesterol
     */
    private Float lowLDLCholesterol;

    /**
     * 低密度脂蛋白上限
     * high_LDLCholesterol
     */
    private Float highLDLCholesterol;

    /**
     * 高密度脂蛋白下限
     * low_HDLCholesterol
     */
    private Float lowHDLCholesterol;

    /**
     * 高密度脂蛋白上限
     * high_HDLCholesterol
     */
    private Float highHDLCholesterol;

    /**
     * 随机血糖下限
     * low_random_sugar
     */
    private Float lowRandomSugar;

    /**
     * 随机血糖上限
     * high_random_sugar
     */
    private Float highRandomSugar;

    /**
     * bmi上限
     */
    private Float highBmi;

    /**
     * bmi下限
     */
    private Float lowBmi;

    /**
     * 腰围上限
     */
    private Float highWaistline;

    /**
     * 腰臀比上限
     */
    private Float highWhr;

    /**
     * 红细胞计数
     */
    private String RBCCount;

    /**
     * 血红蛋白浓度下限
     */
    private Float lowMCHC;

    /**
     * 血红蛋白浓度上限
     */
    private Float highMCHC;

    /**
     * 肌酐下限
     */
    private Float lowCr;

    /**
     * 肌酐上限
     */
    private Float highCr;

    /**
     * 尿酸下限
     */
    private Float lowUA;

    /**
     * 尿酸上限
     */
    private Float highUA;

    /**
     * 血沉下限
     */
    private Float lowESR;

    /**
     * 血沉上限
     */
    private Float highESR;

    /**
     * 铁下限
     */
    private Float lowFe;

    /**
     * 铁上限
     */
    private Float highFe;

    /**
     * 血酮上限
     */
    private String highKetone;

    public String getHighKetone() {
        return highKetone;
    }

    public void setHighKetone(String highKetone) {
        this.highKetone = highKetone;
    }

    public String getRBCCount() {
        return RBCCount;
    }

    public void setRBCCount(String RBCCount) {
        this.RBCCount = RBCCount;
    }

    public Float getLowMCHC() {
        return lowMCHC;
    }

    public void setLowMCHC(Float lowMCHC) {
        this.lowMCHC = lowMCHC;
    }

    public Float getHighMCHC() {
        return highMCHC;
    }

    public void setHighMCHC(Float highMCHC) {
        this.highMCHC = highMCHC;
    }

    public Float getLowCr() {
        return lowCr;
    }

    public void setLowCr(Float lowCr) {
        this.lowCr = lowCr;
    }

    public Float getHighCr() {
        return highCr;
    }

    public void setHighCr(Float highCr) {
        this.highCr = highCr;
    }

    public Float getLowUA() {
        return lowUA;
    }

    public void setLowUA(Float lowUA) {
        this.lowUA = lowUA;
    }

    public Float getHighUA() {
        return highUA;
    }

    public void setHighUA(Float highUA) {
        this.highUA = highUA;
    }

    public Float getLowESR() {
        return lowESR;
    }

    public void setLowESR(Float lowESR) {
        this.lowESR = lowESR;
    }

    public Float getHighESR() {
        return highESR;
    }

    public void setHighESR(Float highESR) {
        this.highESR = highESR;
    }

    public Float getLowFe() {
        return lowFe;
    }

    public void setLowFe(Float lowFe) {
        this.lowFe = lowFe;
    }

    public Float getHighFe() {
        return highFe;
    }

    public void setHighFe(Float highFe) {
        this.highFe = highFe;
    }

    public Float getHighWaistline() {
        return highWaistline;
    }

    public void setHighWaistline(Float highWaistline) {
        this.highWaistline = highWaistline;
    }

    public Float getHighWhr() {
        return highWhr;
    }

    public void setHighWhr(Float highWhr) {
        this.highWhr = highWhr;
    }

    public Float getHighBmi() {
        return highBmi;
    }

    public void setHighBmi(Float highBmi) {
        this.highBmi = highBmi;
    }

    public Float getLowBmi() {
        return lowBmi;
    }

    public void setLowBmi(Float lowBmi) {
        this.lowBmi = lowBmi;
    }

    public Float getLowBeforeBreakfast() {
        return lowBeforeBreakfast;
    }

    public void setLowBeforeBreakfast(Float lowBeforeBreakfast) {
        this.lowBeforeBreakfast = lowBeforeBreakfast;
    }

    public Float getHighBeforeBreakfast() {
        return highBeforeBreakfast;
    }

    public void setHighBeforeBreakfast(Float highBeforeBreakfast) {
        this.highBeforeBreakfast = highBeforeBreakfast;
    }

    public Float getLowBeforedawn() {
        return lowBeforedawn;
    }

    public void setLowBeforedawn(Float lowBeforedawn) {
        this.lowBeforedawn = lowBeforedawn;
    }

    public Float getHighBeforedawn() {
        return highBeforedawn;
    }

    public void setHighBeforedawn(Float highBeforedawn) {
        this.highBeforedawn = highBeforedawn;
    }

    public Float getLowAfterMeal() {
        return lowAfterMeal;
    }

    public void setLowAfterMeal(Float lowAfterMeal) {
        this.lowAfterMeal = lowAfterMeal;
    }

    public Float getHighAfterMeal() {
        return highAfterMeal;
    }

    public void setHighAfterMeal(Float highAfterMeal) {
        this.highAfterMeal = highAfterMeal;
    }

    public Float getLowBeforeSleep() {
        return lowBeforeSleep;
    }

    public void setLowBeforeSleep(Float lowBeforeSleep) {
        this.lowBeforeSleep = lowBeforeSleep;
    }

    public Float getHighBeforeSleep() {
        return highBeforeSleep;
    }

    public void setHighBeforeSleep(Float highBeforeSleep) {
        this.highBeforeSleep = highBeforeSleep;
    }

    public Float getLowBeforeMeal() {
        return lowBeforeMeal;
    }

    public void setLowBeforeMeal(Float lowBeforeMeal) {
        this.lowBeforeMeal = lowBeforeMeal;
    }

    public Float getHighBeforeMeal() {
        return highBeforeMeal;
    }

    public void setHighBeforeMeal(Float highBeforeMeal) {
        this.highBeforeMeal = highBeforeMeal;
    }

    public Float getHighSystolicPress() {
        return highSystolicPress;
    }

    public void setHighSystolicPress(Float highSystolicPress) {
        this.highSystolicPress = highSystolicPress;
    }

    public Float getLowSystolicPress() {
        return lowSystolicPress;
    }

    public void setLowSystolicPress(Float lowSystolicPress) {
        this.lowSystolicPress = lowSystolicPress;
    }

    public Float getHighDiastolicPress() {
        return highDiastolicPress;
    }

    public void setHighDiastolicPress(Float highDiastolicPress) {
        this.highDiastolicPress = highDiastolicPress;
    }

    public Float getLowDiastolicPress() {
        return lowDiastolicPress;
    }

    public void setLowDiastolicPress(Float lowDiastolicPress) {
        this.lowDiastolicPress = lowDiastolicPress;
    }

    public Float getLowGlycosylatedVal() {
        return lowGlycosylatedVal;
    }

    public void setLowGlycosylatedVal(Float lowGlycosylatedVal) {
        this.lowGlycosylatedVal = lowGlycosylatedVal;
    }

    public Float getHighGlycosylatedVal() {
        return highGlycosylatedVal;
    }

    public void setHighGlycosylatedVal(Float highGlycosylatedVal) {
        this.highGlycosylatedVal = highGlycosylatedVal;
    }

    public Float getLowTCholesterol() {
        return lowTCholesterol;
    }

    public void setLowTCholesterol(Float lowTCholesterol) {
        this.lowTCholesterol = lowTCholesterol;
    }

    public Float getHighTCholesterol() {
        return highTCholesterol;
    }

    public void setHighTCholesterol(Float highTCholesterol) {
        this.highTCholesterol = highTCholesterol;
    }

    public Float getLowTriglyceride() {
        return lowTriglyceride;
    }

    public void setLowTriglyceride(Float lowTriglyceride) {
        this.lowTriglyceride = lowTriglyceride;
    }

    public Float getHighTriglyceride() {
        return highTriglyceride;
    }

    public void setHighTriglyceride(Float highTriglyceride) {
        this.highTriglyceride = highTriglyceride;
    }

    public Float getLowLDLCholesterol() {
        return lowLDLCholesterol;
    }

    public void setLowLDLCholesterol(Float lowLDLCholesterol) {
        this.lowLDLCholesterol = lowLDLCholesterol;
    }

    public Float getHighLDLCholesterol() {
        return highLDLCholesterol;
    }

    public void setHighLDLCholesterol(Float highLDLCholesterol) {
        this.highLDLCholesterol = highLDLCholesterol;
    }

    public Float getLowHDLCholesterol() {
        return lowHDLCholesterol;
    }

    public void setLowHDLCholesterol(Float lowHDLCholesterol) {
        this.lowHDLCholesterol = lowHDLCholesterol;
    }

    public Float getHighHDLCholesterol() {
        return highHDLCholesterol;
    }

    public void setHighHDLCholesterol(Float highHDLCholesterol) {
        this.highHDLCholesterol = highHDLCholesterol;
    }

    public Float getLowRandomSugar() {
        return lowRandomSugar;
    }

    public void setLowRandomSugar(Float lowRandomSugar) {
        this.lowRandomSugar = lowRandomSugar;
    }

    public Float getHighRandomSugar() {
        return highRandomSugar;
    }

    public void setHighRandomSugar(Float highRandomSugar) {
        this.highRandomSugar = highRandomSugar;
    }

    public Float getLowAfterMealOneHour() {
        return lowAfterMealOneHour;
    }

    public void setLowAfterMealOneHour(Float lowAfterMealOneHour) {
        this.lowAfterMealOneHour = lowAfterMealOneHour;
    }

    public Float getHighAfterMealOneHour() {
        return highAfterMealOneHour;
    }

    public void setHighAfterMealOneHour(Float highAfterMealOneHour) {
        this.highAfterMealOneHour = highAfterMealOneHour;
    }
}