package com.comvee.cdms.prescription.bo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hba1c
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Hba1cBO {

    /**
     * 记录的值
     * record_value
     */
    private Float recordValue;

    /**
     * 记录值等级 3 正常 5 偏高
     * record_level
     */
    private Integer recordLevel;


    /**
     * 记录日期
     * record_dt
     */
    private String recordDt;

    /**
     * 备注
     * remark
     */
    private String remark;

    /**
     * 参数范围最大值
     * range_max
     */
    private String rangeMax;

    public Float getRecordValue() {
        return recordValue;
    }

    public void setRecordValue(Float recordValue) {
        this.recordValue = recordValue;
    }

    public Integer getRecordLevel() {
        return recordLevel;
    }

    public void setRecordLevel(Integer recordLevel) {
        this.recordLevel = recordLevel;
    }

    public String getRecordDt() {
        return recordDt;
    }

    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRangeMax() {
        return rangeMax;
    }

    public void setRangeMax(String rangeMax) {
        this.rangeMax = rangeMax;
    }
}