package com.comvee.cdms.sign.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bmi
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddBmiServiceDTO {

    private String sid;

    /**
     * 体重
     * weight
     */
    private Float weight;

    /**
     * 身高
     * height
     */
    private Float height;

    /**
     * bmi
     */
    private String bmi;

    /**
     * 记录时间
     * record_dt
     */
    private String recordDt;



    /**
     * 患者id
     * member_id
     */
    private String memberId;


    /**
     * 来源
     * origin
     */
    private Integer origin;


    /**
     * 操作者类型 1 用户 2 医护
     * operator_type
     */
    private Integer operatorType;

    /**
     * operator_id
     */
    private String operatorId;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public Float getWeight() {
        return weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }

    public Float getHeight() {
        return height;
    }

    public void setHeight(Float height) {
        this.height = height;
    }

    public String getBmi() {
        return bmi;
    }

    public void setBmi(String bmi) {
        this.bmi = bmi;
    }

    public String getRecordDt() {
        return recordDt;
    }

    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public Integer getOrigin() {
        return origin;
    }

    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    public Integer getOperatorType() {
        return operatorType;
    }

    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }
}