package com.comvee.cdms.sign.dto;

import javax.validation.constraints.NotEmpty;

import javax.validation.constraints.NotNull;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bmi
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddBmiDTO {

    @NotEmpty(message = "memberId 不能为空")
    private String memberId;

    /**
     * 体重
     * weight
     */
    @NotNull
    private Float weight;

    /**
     * 身高
     * height
     */
    @NotNull
    private Float height;

    /**
     * bmi
     */
    @NotEmpty
    private String bmi;

    /**
     * 记录时间
     * record_dt
     */
    @NotEmpty
    private String recordDt;

//    @NotNull(message = "来源不可为空,origin")
    private Integer origin;

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public Integer getOrigin() {
        return origin;
    }

    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    public Float getWeight() {
        return weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }

    public Float getHeight() {
        return height;
    }

    public void setHeight(Float height) {
        this.height = height;
    }

    public String getBmi() {
        return bmi;
    }

    public void setBmi(String bmi) {
        this.bmi = bmi;
    }

    public String getRecordDt() {
        return recordDt;
    }

    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

}