package com.comvee.cdms.sign.dto;

import javax.validation.constraints.NotEmpty;

import javax.validation.constraints.NotNull;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hba1c
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AddHba1cDTO {

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 记录的值
     * record_value
     */
    @NotNull
    private Float recordValue;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 操作类型 1 患者 2 医生
     * operator_type
     */
    private Integer operatorType;

    /**
     * 记录日期
     * record_dt
     */
    @NotEmpty
    private String recordDt;

    /**
     * 备注
     * remark
     */
    private String remark;

    /**
     * 来源
     */
//    @NotNull(message = "来源不可为空")
    private Integer origin;

    /**
     * 控制目标上限
     */
    private String rangeMax;

    /**
     * 主键，只有同步掌控记录的时候会传
     */
    private String sid;
    private String hospitalId = "-1";
    private String hospitalName;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getRangeMax() {
        return rangeMax;
    }

    public void setRangeMax(String rangeMax) {
        this.rangeMax = rangeMax;
    }

    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public Float getRecordValue() {
        return recordValue;
    }

    public void setRecordValue(Float recordValue) {
        this.recordValue = recordValue;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public Integer getOperatorType() {
        return operatorType;
    }

    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    public String getRecordDt() {
        return recordDt;
    }

    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    public Integer getOrigin() {
        return origin;
    }

    public String getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
}