package com.comvee.cdms.other.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dict
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DictPO {
    /**
     * 主键
     * dict_id
     */
    private String dictId;

    /**
     * 字典项
     * dict_code
     */
    private String dictCode;

    /**
     * 字典值
     * dict_value
     */
    private String dictValue;

    /**
     * 描述
     * dict_desc
     */
    private String dictDesc;

    /**
     * 父级code
     * parent_code
     */
    private String parentCode;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.dict_id
     *
     * @return the value of t_dict.dict_id
     *
     * @mbggenerated
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.dict_id
     *
     * @param dictId the value for t_dict.dict_id
     *
     * @mbggenerated
     */
    public void setDictId(String dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.dict_code
     *
     * @return the value of t_dict.dict_code
     *
     * @mbggenerated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.dict_code
     *
     * @param dictCode the value for t_dict.dict_code
     *
     * @mbggenerated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.dict_value
     *
     * @return the value of t_dict.dict_value
     *
     * @mbggenerated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.dict_value
     *
     * @param dictValue the value for t_dict.dict_value
     *
     * @mbggenerated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.dict_desc
     *
     * @return the value of t_dict.dict_desc
     *
     * @mbggenerated
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.dict_desc
     *
     * @param dictDesc the value for t_dict.dict_desc
     *
     * @mbggenerated
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.parent_code
     *
     * @return the value of t_dict.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.parent_code
     *
     * @param parentCode the value for t_dict.parent_code
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.insert_dt
     *
     * @return the value of t_dict.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.insert_dt
     *
     * @param insertDt the value for t_dict.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.update_dt
     *
     * @return the value of t_dict.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.update_dt
     *
     * @param updateDt the value for t_dict.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict.valid
     *
     * @return the value of t_dict.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict.valid
     *
     * @param valid the value for t_dict.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}