package com.comvee.cdms.other.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_push_token
 *
 * @mbggenerated do_not_delete_during_merge
 * @author Su
 */
public class DoctorPushTokenPO {

    /**
     * sid
     */
    private String sid;

    /**
     * doctor_id
     */
    private String doctorId;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * push_token
     */
    private String pushToken;

    /**
     * 设备类型 1 安卓 2 ios
     * device_type
     */
    private Integer deviceType;

    /**
     * 渠道code
     * channel_code
     */
    private String channelCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.sid
     *
     * @return the value of t_doctor_push_token.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.sid
     *
     * @param sid the value for t_doctor_push_token.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.doctor_id
     *
     * @return the value of t_doctor_push_token.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.doctor_id
     *
     * @param doctorId the value for t_doctor_push_token.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.insert_dt
     *
     * @return the value of t_doctor_push_token.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.insert_dt
     *
     * @param insertDt the value for t_doctor_push_token.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.update_dt
     *
     * @return the value of t_doctor_push_token.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.update_dt
     *
     * @param updateDt the value for t_doctor_push_token.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.push_token
     *
     * @return the value of t_doctor_push_token.push_token
     *
     * @mbggenerated
     */
    public String getPushToken() {
        return pushToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.push_token
     *
     * @param pushToken the value for t_doctor_push_token.push_token
     *
     * @mbggenerated
     */
    public void setPushToken(String pushToken) {
        this.pushToken = pushToken == null ? null : pushToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.device_type
     *
     * @return the value of t_doctor_push_token.device_type
     *
     * @mbggenerated
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.device_type
     *
     * @param deviceType the value for t_doctor_push_token.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_token.channel_code
     *
     * @return the value of t_doctor_push_token.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_token.channel_code
     *
     * @param channelCode the value for t_doctor_push_token.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }
}