package com.comvee.cdms.other.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_doctor_push_set
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DoctorPushSetPO {
    /**
     * sid
     */
    private String sid;

    /**
     * doctor_id
     */
    private String doctorId;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 体征异常推送设置  1 开启 0 关闭
     * sign_push
     */
    private Integer signPush;

    /**
     * 对话推送设置  1 开启 0 关闭
     * dialogue_push
     */
    private Integer dialoguePush;

    /**
     * 微信推送 1 开 0 关闭
     */
    private Integer wxPush;

    public Integer getWxPush() {
        return wxPush;
    }

    public void setWxPush(Integer wxPush) {
        this.wxPush = wxPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.sid
     *
     * @return the value of t_doctor_push_set.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.sid
     *
     * @param sid the value for t_doctor_push_set.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.doctor_id
     *
     * @return the value of t_doctor_push_set.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.doctor_id
     *
     * @param doctorId the value for t_doctor_push_set.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.insert_dt
     *
     * @return the value of t_doctor_push_set.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.insert_dt
     *
     * @param insertDt the value for t_doctor_push_set.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.update_dt
     *
     * @return the value of t_doctor_push_set.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.update_dt
     *
     * @param updateDt the value for t_doctor_push_set.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.sign_push
     *
     * @return the value of t_doctor_push_set.sign_push
     *
     * @mbggenerated
     */
    public Integer getSignPush() {
        return signPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.sign_push
     *
     * @param signPush the value for t_doctor_push_set.sign_push
     *
     * @mbggenerated
     */
    public void setSignPush(Integer signPush) {
        this.signPush = signPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_push_set.dialogue_push
     *
     * @return the value of t_doctor_push_set.dialogue_push
     *
     * @mbggenerated
     */
    public Integer getDialoguePush() {
        return dialoguePush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_push_set.dialogue_push
     *
     * @param dialoguePush the value for t_doctor_push_set.dialogue_push
     *
     * @mbggenerated
     */
    public void setDialoguePush(Integer dialoguePush) {
        this.dialoguePush = dialoguePush;
    }
}