package com.comvee.cdms.dybloodsugar.po;

public class DYMemberSensorPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.sensor_no
     *
     * @mbg.generated
     */
    private String sensorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.monitoring_time
     *
     * @mbg.generated
     */
    private String monitoringTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.modify_dt
     *
     * @mbg.generated
     */
    private String modifyDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.insert_dt
     *
     * @mbg.generated
     */
    private String insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.is_valid
     *
     * @mbg.generated
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.run_status
     *
     * @mbg.generated
     */
    private Byte runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.operation_type
     *
     * @mbg.generated
     */
    private Byte operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_member_sensor.operation_id
     *
     * @mbg.generated
     */
    private String operationId;

    private Integer bindType;

    private String appId;


    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.sid
     *
     * @return the value of dy_member_sensor.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.sid
     *
     * @param sid the value for dy_member_sensor.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.sensor_no
     *
     * @return the value of dy_member_sensor.sensor_no
     *
     * @mbg.generated
     */
    public String getSensorNo() {
        return sensorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.sensor_no
     *
     * @param sensorNo the value for dy_member_sensor.sensor_no
     *
     * @mbg.generated
     */
    public void setSensorNo(String sensorNo) {
        this.sensorNo = sensorNo == null ? null : sensorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.member_id
     *
     * @return the value of dy_member_sensor.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.member_id
     *
     * @param memberId the value for dy_member_sensor.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.monitoring_time
     *
     * @return the value of dy_member_sensor.monitoring_time
     *
     * @mbg.generated
     */
    public String getMonitoringTime() {
        return monitoringTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.monitoring_time
     *
     * @param monitoringTime the value for dy_member_sensor.monitoring_time
     *
     * @mbg.generated
     */
    public void setMonitoringTime(String monitoringTime) {
        this.monitoringTime = monitoringTime == null ? null : monitoringTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.modify_dt
     *
     * @return the value of dy_member_sensor.modify_dt
     *
     * @mbg.generated
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.modify_dt
     *
     * @param modifyDt the value for dy_member_sensor.modify_dt
     *
     * @mbg.generated
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt == null ? null : modifyDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.insert_dt
     *
     * @return the value of dy_member_sensor.insert_dt
     *
     * @mbg.generated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.insert_dt
     *
     * @param insertDt the value for dy_member_sensor.insert_dt
     *
     * @mbg.generated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.is_valid
     *
     * @return the value of dy_member_sensor.is_valid
     *
     * @mbg.generated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.is_valid
     *
     * @param isValid the value for dy_member_sensor.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.run_status
     *
     * @return the value of dy_member_sensor.run_status
     *
     * @mbg.generated
     */
    public Byte getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.run_status
     *
     * @param runStatus the value for dy_member_sensor.run_status
     *
     * @mbg.generated
     */
    public void setRunStatus(Byte runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.operation_type
     *
     * @return the value of dy_member_sensor.operation_type
     *
     * @mbg.generated
     */
    public Byte getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.operation_type
     *
     * @param operationType the value for dy_member_sensor.operation_type
     *
     * @mbg.generated
     */
    public void setOperationType(Byte operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_member_sensor.operation_id
     *
     * @return the value of dy_member_sensor.operation_id
     *
     * @mbg.generated
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_member_sensor.operation_id
     *
     * @param operationId the value for dy_member_sensor.operation_id
     *
     * @mbg.generated
     */
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }

    public Integer getBindType() {
        return bindType;
    }

    public void setBindType(Integer bindType) {
        this.bindType = bindType;
    }

    @Override
    public String toString() {
        return "DYMemberSensorPO{" +
                ", sensorNo='" + sensorNo + '\'' +
                ", memberId='" + memberId + '\'' +
                ", insertDt='" + insertDt + '\'' +
                '}';
    }
}