package com.comvee.cdms.dybloodsugar.po;

public class DYYPMachinePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.machine_no
     *
     * @mbg.generated
     */
    private String machineNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.machine_eq
     *
     * @mbg.generated
     */
    private String machineEq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.hospital_id
     *
     * @mbg.generated
     */
    private String hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.department_id
     *
     * @mbg.generated
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.is_valid
     *
     * @mbg.generated
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.insert_dt
     *
     * @mbg.generated
     */
    private String insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_machine.modify_dt
     *
     * @mbg.generated
     */
    private String modifyDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.sid
     *
     * @return the value of dy_yp_machine.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.sid
     *
     * @param sid the value for dy_yp_machine.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.machine_no
     *
     * @return the value of dy_yp_machine.machine_no
     *
     * @mbg.generated
     */
    public String getMachineNo() {
        return machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.machine_no
     *
     * @param machineNo the value for dy_yp_machine.machine_no
     *
     * @mbg.generated
     */
    public void setMachineNo(String machineNo) {
        this.machineNo = machineNo == null ? null : machineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.machine_eq
     *
     * @return the value of dy_yp_machine.machine_eq
     *
     * @mbg.generated
     */
    public String getMachineEq() {
        return machineEq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.machine_eq
     *
     * @param machineEq the value for dy_yp_machine.machine_eq
     *
     * @mbg.generated
     */
    public void setMachineEq(String machineEq) {
        this.machineEq = machineEq == null ? null : machineEq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.hospital_id
     *
     * @return the value of dy_yp_machine.hospital_id
     *
     * @mbg.generated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.hospital_id
     *
     * @param hospitalId the value for dy_yp_machine.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.department_id
     *
     * @return the value of dy_yp_machine.department_id
     *
     * @mbg.generated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.department_id
     *
     * @param departmentId the value for dy_yp_machine.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.is_valid
     *
     * @return the value of dy_yp_machine.is_valid
     *
     * @mbg.generated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.is_valid
     *
     * @param isValid the value for dy_yp_machine.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.insert_dt
     *
     * @return the value of dy_yp_machine.insert_dt
     *
     * @mbg.generated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.insert_dt
     *
     * @param insertDt the value for dy_yp_machine.insert_dt
     *
     * @mbg.generated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_machine.modify_dt
     *
     * @return the value of dy_yp_machine.modify_dt
     *
     * @mbg.generated
     */
    public String getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_machine.modify_dt
     *
     * @param modifyDt the value for dy_yp_machine.modify_dt
     *
     * @mbg.generated
     */
    public void setModifyDt(String modifyDt) {
        this.modifyDt = modifyDt == null ? null : modifyDt.trim();
    }
}