package com.comvee.cdms.dybloodsugar.po;

public class DYYPStatisticsPOWithBLOBs extends DYYPStatisticsPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.chart_data
     *
     * @mbg.generated
     */
    private String chartData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.day_sugar_avg_diff_val_json
     *
     * @mbg.generated
     */
    private String daySugarAvgDiffValJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.chart_data
     *
     * @return the value of dy_yp_statistics.chart_data
     *
     * @mbg.generated
     */
    public String getChartData() {
        return chartData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.chart_data
     *
     * @param chartData the value for dy_yp_statistics.chart_data
     *
     * @mbg.generated
     */
    public void setChartData(String chartData) {
        this.chartData = chartData == null ? null : chartData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.day_sugar_avg_diff_val_json
     *
     * @return the value of dy_yp_statistics.day_sugar_avg_diff_val_json
     *
     * @mbg.generated
     */
    public String getDaySugarAvgDiffValJson() {
        return daySugarAvgDiffValJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.day_sugar_avg_diff_val_json
     *
     * @param daySugarAvgDiffValJson the value for dy_yp_statistics.day_sugar_avg_diff_val_json
     *
     * @mbg.generated
     */
    public void setDaySugarAvgDiffValJson(String daySugarAvgDiffValJson) {
        this.daySugarAvgDiffValJson = daySugarAvgDiffValJson == null ? null : daySugarAvgDiffValJson.trim();
    }
}