package com.comvee.cdms.dybloodsugar.po;

import java.util.Date;

public class DYYPStatisticsPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.sensor_no
     *
     * @mbg.generated
     */
    private String sensorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.start_dt
     *
     * @mbg.generated
     */
    private Date startDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.day
     *
     * @mbg.generated
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.avg_num
     *
     * @mbg.generated
     */
    private Double avgNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.ghb
     *
     * @mbg.generated
     */
    private Double ghb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.standard_val
     *
     * @mbg.generated
     */
    private String standardVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_normal
     *
     * @mbg.generated
     */
    private String awiTimeRateOfNormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_high
     *
     * @mbg.generated
     */
    private String awiTimeRateOfHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_low
     *
     * @mbg.generated
     */
    private String awiTimeRateOfLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.event_count_of_normal
     *
     * @mbg.generated
     */
    private Integer eventCountOfNormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.event_count_of_high
     *
     * @mbg.generated
     */
    private Integer eventCountOfHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.event_count_of_low
     *
     * @mbg.generated
     */
    private Integer eventCountOfLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.avg_awi_time_of_normal
     *
     * @mbg.generated
     */
    private String avgAwiTimeOfNormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.avg_awi_time_of_high
     *
     * @mbg.generated
     */
    private String avgAwiTimeOfHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.avg_awi_time_of_low
     *
     * @mbg.generated
     */
    private String avgAwiTimeOfLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.mean_amplitude_of_glycemic_excursion
     *
     * @mbg.generated
     */
    private String meanAmplitudeOfGlycemicExcursion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_4_0
     *
     * @mbg.generated
     */
    private String awiTimeRateOf40;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_13_9
     *
     * @mbg.generated
     */
    private String awiTimeRateOf139;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.awi_time_rate_of_3_9
     *
     * @mbg.generated
     */
    private String awiTimeRateOf39;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.coefficient_of_variation
     *
     * @mbg.generated
     */
    private String coefficientOfVariation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.is_valid
     *
     * @mbg.generated
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.insert_dt
     *
     * @mbg.generated
     */
    private Date insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_yp_statistics.modify_dt
     *
     * @mbg.generated
     */
    private Date modifyDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.sid
     *
     * @return the value of dy_yp_statistics.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.sid
     *
     * @param sid the value for dy_yp_statistics.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.sensor_no
     *
     * @return the value of dy_yp_statistics.sensor_no
     *
     * @mbg.generated
     */
    public String getSensorNo() {
        return sensorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.sensor_no
     *
     * @param sensorNo the value for dy_yp_statistics.sensor_no
     *
     * @mbg.generated
     */
    public void setSensorNo(String sensorNo) {
        this.sensorNo = sensorNo == null ? null : sensorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.type
     *
     * @return the value of dy_yp_statistics.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.type
     *
     * @param type the value for dy_yp_statistics.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.start_dt
     *
     * @return the value of dy_yp_statistics.start_dt
     *
     * @mbg.generated
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.start_dt
     *
     * @param startDt the value for dy_yp_statistics.start_dt
     *
     * @mbg.generated
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.day
     *
     * @return the value of dy_yp_statistics.day
     *
     * @mbg.generated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.day
     *
     * @param day the value for dy_yp_statistics.day
     *
     * @mbg.generated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.avg_num
     *
     * @return the value of dy_yp_statistics.avg_num
     *
     * @mbg.generated
     */
    public Double getAvgNum() {
        return avgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.avg_num
     *
     * @param avgNum the value for dy_yp_statistics.avg_num
     *
     * @mbg.generated
     */
    public void setAvgNum(Double avgNum) {
        this.avgNum = avgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.ghb
     *
     * @return the value of dy_yp_statistics.ghb
     *
     * @mbg.generated
     */
    public Double getGhb() {
        return ghb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.ghb
     *
     * @param ghb the value for dy_yp_statistics.ghb
     *
     * @mbg.generated
     */
    public void setGhb(Double ghb) {
        this.ghb = ghb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.standard_val
     *
     * @return the value of dy_yp_statistics.standard_val
     *
     * @mbg.generated
     */
    public String getStandardVal() {
        return standardVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.standard_val
     *
     * @param standardVal the value for dy_yp_statistics.standard_val
     *
     * @mbg.generated
     */
    public void setStandardVal(String standardVal) {
        this.standardVal = standardVal == null ? null : standardVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_normal
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_normal
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOfNormal() {
        return awiTimeRateOfNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_normal
     *
     * @param awiTimeRateOfNormal the value for dy_yp_statistics.awi_time_rate_of_normal
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOfNormal(String awiTimeRateOfNormal) {
        this.awiTimeRateOfNormal = awiTimeRateOfNormal == null ? null : awiTimeRateOfNormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_high
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_high
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOfHigh() {
        return awiTimeRateOfHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_high
     *
     * @param awiTimeRateOfHigh the value for dy_yp_statistics.awi_time_rate_of_high
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOfHigh(String awiTimeRateOfHigh) {
        this.awiTimeRateOfHigh = awiTimeRateOfHigh == null ? null : awiTimeRateOfHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_low
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_low
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOfLow() {
        return awiTimeRateOfLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_low
     *
     * @param awiTimeRateOfLow the value for dy_yp_statistics.awi_time_rate_of_low
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOfLow(String awiTimeRateOfLow) {
        this.awiTimeRateOfLow = awiTimeRateOfLow == null ? null : awiTimeRateOfLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.event_count_of_normal
     *
     * @return the value of dy_yp_statistics.event_count_of_normal
     *
     * @mbg.generated
     */
    public Integer getEventCountOfNormal() {
        return eventCountOfNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.event_count_of_normal
     *
     * @param eventCountOfNormal the value for dy_yp_statistics.event_count_of_normal
     *
     * @mbg.generated
     */
    public void setEventCountOfNormal(Integer eventCountOfNormal) {
        this.eventCountOfNormal = eventCountOfNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.event_count_of_high
     *
     * @return the value of dy_yp_statistics.event_count_of_high
     *
     * @mbg.generated
     */
    public Integer getEventCountOfHigh() {
        return eventCountOfHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.event_count_of_high
     *
     * @param eventCountOfHigh the value for dy_yp_statistics.event_count_of_high
     *
     * @mbg.generated
     */
    public void setEventCountOfHigh(Integer eventCountOfHigh) {
        this.eventCountOfHigh = eventCountOfHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.event_count_of_low
     *
     * @return the value of dy_yp_statistics.event_count_of_low
     *
     * @mbg.generated
     */
    public Integer getEventCountOfLow() {
        return eventCountOfLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.event_count_of_low
     *
     * @param eventCountOfLow the value for dy_yp_statistics.event_count_of_low
     *
     * @mbg.generated
     */
    public void setEventCountOfLow(Integer eventCountOfLow) {
        this.eventCountOfLow = eventCountOfLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.avg_awi_time_of_normal
     *
     * @return the value of dy_yp_statistics.avg_awi_time_of_normal
     *
     * @mbg.generated
     */
    public String getAvgAwiTimeOfNormal() {
        return avgAwiTimeOfNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.avg_awi_time_of_normal
     *
     * @param avgAwiTimeOfNormal the value for dy_yp_statistics.avg_awi_time_of_normal
     *
     * @mbg.generated
     */
    public void setAvgAwiTimeOfNormal(String avgAwiTimeOfNormal) {
        this.avgAwiTimeOfNormal = avgAwiTimeOfNormal == null ? null : avgAwiTimeOfNormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.avg_awi_time_of_high
     *
     * @return the value of dy_yp_statistics.avg_awi_time_of_high
     *
     * @mbg.generated
     */
    public String getAvgAwiTimeOfHigh() {
        return avgAwiTimeOfHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.avg_awi_time_of_high
     *
     * @param avgAwiTimeOfHigh the value for dy_yp_statistics.avg_awi_time_of_high
     *
     * @mbg.generated
     */
    public void setAvgAwiTimeOfHigh(String avgAwiTimeOfHigh) {
        this.avgAwiTimeOfHigh = avgAwiTimeOfHigh == null ? null : avgAwiTimeOfHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.avg_awi_time_of_low
     *
     * @return the value of dy_yp_statistics.avg_awi_time_of_low
     *
     * @mbg.generated
     */
    public String getAvgAwiTimeOfLow() {
        return avgAwiTimeOfLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.avg_awi_time_of_low
     *
     * @param avgAwiTimeOfLow the value for dy_yp_statistics.avg_awi_time_of_low
     *
     * @mbg.generated
     */
    public void setAvgAwiTimeOfLow(String avgAwiTimeOfLow) {
        this.avgAwiTimeOfLow = avgAwiTimeOfLow == null ? null : avgAwiTimeOfLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.mean_amplitude_of_glycemic_excursion
     *
     * @return the value of dy_yp_statistics.mean_amplitude_of_glycemic_excursion
     *
     * @mbg.generated
     */
    public String getMeanAmplitudeOfGlycemicExcursion() {
        return meanAmplitudeOfGlycemicExcursion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.mean_amplitude_of_glycemic_excursion
     *
     * @param meanAmplitudeOfGlycemicExcursion the value for dy_yp_statistics.mean_amplitude_of_glycemic_excursion
     *
     * @mbg.generated
     */
    public void setMeanAmplitudeOfGlycemicExcursion(String meanAmplitudeOfGlycemicExcursion) {
        this.meanAmplitudeOfGlycemicExcursion = meanAmplitudeOfGlycemicExcursion == null ? null : meanAmplitudeOfGlycemicExcursion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_4_0
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_4_0
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOf40() {
        return awiTimeRateOf40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_4_0
     *
     * @param awiTimeRateOf40 the value for dy_yp_statistics.awi_time_rate_of_4_0
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOf40(String awiTimeRateOf40) {
        this.awiTimeRateOf40 = awiTimeRateOf40 == null ? null : awiTimeRateOf40.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_13_9
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_13_9
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOf139() {
        return awiTimeRateOf139;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_13_9
     *
     * @param awiTimeRateOf139 the value for dy_yp_statistics.awi_time_rate_of_13_9
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOf139(String awiTimeRateOf139) {
        this.awiTimeRateOf139 = awiTimeRateOf139 == null ? null : awiTimeRateOf139.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.awi_time_rate_of_3_9
     *
     * @return the value of dy_yp_statistics.awi_time_rate_of_3_9
     *
     * @mbg.generated
     */
    public String getAwiTimeRateOf39() {
        return awiTimeRateOf39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.awi_time_rate_of_3_9
     *
     * @param awiTimeRateOf39 the value for dy_yp_statistics.awi_time_rate_of_3_9
     *
     * @mbg.generated
     */
    public void setAwiTimeRateOf39(String awiTimeRateOf39) {
        this.awiTimeRateOf39 = awiTimeRateOf39 == null ? null : awiTimeRateOf39.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.coefficient_of_variation
     *
     * @return the value of dy_yp_statistics.coefficient_of_variation
     *
     * @mbg.generated
     */
    public String getCoefficientOfVariation() {
        return coefficientOfVariation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.coefficient_of_variation
     *
     * @param coefficientOfVariation the value for dy_yp_statistics.coefficient_of_variation
     *
     * @mbg.generated
     */
    public void setCoefficientOfVariation(String coefficientOfVariation) {
        this.coefficientOfVariation = coefficientOfVariation == null ? null : coefficientOfVariation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.is_valid
     *
     * @return the value of dy_yp_statistics.is_valid
     *
     * @mbg.generated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.is_valid
     *
     * @param isValid the value for dy_yp_statistics.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.insert_dt
     *
     * @return the value of dy_yp_statistics.insert_dt
     *
     * @mbg.generated
     */
    public Date getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.insert_dt
     *
     * @param insertDt the value for dy_yp_statistics.insert_dt
     *
     * @mbg.generated
     */
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_yp_statistics.modify_dt
     *
     * @return the value of dy_yp_statistics.modify_dt
     *
     * @mbg.generated
     */
    public Date getModifyDt() {
        return modifyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_yp_statistics.modify_dt
     *
     * @param modifyDt the value for dy_yp_statistics.modify_dt
     *
     * @mbg.generated
     */
    public void setModifyDt(Date modifyDt) {
        this.modifyDt = modifyDt;
    }
}