package com.comvee.cdms.hospital.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hospital
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class HospitalPO {
    /**
     * hospital_id
     */
    private String hospitalId;

    /**
     * 医院名称
     * hospital_name
     */
    private String hospitalName;

    /**
     * 医院类型
     * hospital_type
     */
    private Integer hospitalType;

    /**
     * 类型名称
     * type_name
     */
    private String typeName;

    /**
     * 医院性质
     * hospital_nature
     */
    private Integer hospitalNature;

    /**
     * 性质名称
     * nature_name
     */
    private String natureName;

    /**
     * 省份id
     * province_id
     */
    private String provinceId;

    /**
     * 省份名称
     * province_name
     */
    private String provinceName;

    /**
     * 城市id
     * city_id
     */
    private String cityId;

    /**
     * 城市名
     * city_name
     */
    private String cityName;

    /**
     * 区域id
     * area_id
     */
    private String areaId;

    /**
     * 区域名称
     * area_name
     */
    private String areaName;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 人数
     * people_number
     */
    private Integer peopleNumber;

    /**
     * 医院等级  1 社区 2 街道  3 乡镇 4 县级 5市级
     */
    private Integer level;
    private Integer memberNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.hospital_id
     *
     * @return the value of t_hospital.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.hospital_id
     *
     * @param hospitalId the value for t_hospital.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.hospital_name
     *
     * @return the value of t_hospital.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.hospital_name
     *
     * @param hospitalName the value for t_hospital.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.hospital_type
     *
     * @return the value of t_hospital.hospital_type
     *
     * @mbggenerated
     */
    public Integer getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.hospital_type
     *
     * @param hospitalType the value for t_hospital.hospital_type
     *
     * @mbggenerated
     */
    public void setHospitalType(Integer hospitalType) {
        this.hospitalType = hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.type_name
     *
     * @return the value of t_hospital.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.type_name
     *
     * @param typeName the value for t_hospital.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.hospital_nature
     *
     * @return the value of t_hospital.hospital_nature
     *
     * @mbggenerated
     */
    public Integer getHospitalNature() {
        return hospitalNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.hospital_nature
     *
     * @param hospitalNature the value for t_hospital.hospital_nature
     *
     * @mbggenerated
     */
    public void setHospitalNature(Integer hospitalNature) {
        this.hospitalNature = hospitalNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.nature_name
     *
     * @return the value of t_hospital.nature_name
     *
     * @mbggenerated
     */
    public String getNatureName() {
        return natureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.nature_name
     *
     * @param natureName the value for t_hospital.nature_name
     *
     * @mbggenerated
     */
    public void setNatureName(String natureName) {
        this.natureName = natureName == null ? null : natureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.province_id
     *
     * @return the value of t_hospital.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.province_id
     *
     * @param provinceId the value for t_hospital.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.province_name
     *
     * @return the value of t_hospital.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.province_name
     *
     * @param provinceName the value for t_hospital.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.city_id
     *
     * @return the value of t_hospital.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.city_id
     *
     * @param cityId the value for t_hospital.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.city_name
     *
     * @return the value of t_hospital.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.city_name
     *
     * @param cityName the value for t_hospital.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.area_id
     *
     * @return the value of t_hospital.area_id
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.area_id
     *
     * @param areaId the value for t_hospital.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.area_name
     *
     * @return the value of t_hospital.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.area_name
     *
     * @param areaName the value for t_hospital.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.insert_dt
     *
     * @return the value of t_hospital.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.insert_dt
     *
     * @param insertDt the value for t_hospital.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt == null ? null : insertDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.update_dt
     *
     * @return the value of t_hospital.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.update_dt
     *
     * @param updateDt the value for t_hospital.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.people_number
     *
     * @return the value of t_hospital.people_number
     *
     * @mbggenerated
     */
    public Integer getPeopleNumber() {
        return peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.people_number
     *
     * @param peopleNumber the value for t_hospital.people_number
     *
     * @mbggenerated
     */
    public void setPeopleNumber(Integer peopleNumber) {
        this.peopleNumber = peopleNumber;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getMemberNumber() {
        return memberNumber;
    }

    public void setMemberNumber(Integer memberNumber) {
        this.memberNumber = memberNumber;
    }

}