package com.comvee.cdms.qualitycontrol.model.param;

import javax.validation.constraints.NotEmpty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_quality_control_liquid
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UpdateQualityControlLiquidParam {

    /**
     * sid
     */
    @NotEmpty(message = "主键 不能为空")
    private String sid;
    /**
     * 质检液批次号
     * batch_number
     */
    private String batchNo;

    /**
     * 生产日期
     * product_date
     */
    private String productDate;

    /**
     * 失效日期
     * invalid_date
     */
    private String invalidDate;

    /**
     * 级别编号
     * level_code
     */
    private Integer levelCode;

    /**
     * 级别名称
     * level_name
     */
    private String levelName;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public String getProductDate() {
        return productDate;
    }

    public void setProductDate(String productDate) {
        this.productDate = productDate;
    }

    public String getInvalidDate() {
        return invalidDate;
    }

    public void setInvalidDate(String invalidDate) {
        this.invalidDate = invalidDate;
    }

    public Integer getLevelCode() {
        return levelCode;
    }

    public void setLevelCode(Integer levelCode) {
        this.levelCode = levelCode;
    }

    public String getLevelName() {
        return levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }
}