package com.comvee.cdms.differentlevels.mapper;

import com.comvee.cdms.differentlevels.po.MemberDifferentLevelsPO;
import com.comvee.cdms.differentlevels.po.MemberDifferentLevelsPOExample;
import com.comvee.cdms.differentlevels.po.MemberDifferentLevelsPOWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemberDifferentLevelsPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int countByExample(MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int deleteByExample(MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int insert(MemberDifferentLevelsPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int insertSelective(MemberDifferentLevelsPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    List<MemberDifferentLevelsPOWithBLOBs> selectByExampleWithBLOBs(MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    List<MemberDifferentLevelsPO> selectByExample(MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    MemberDifferentLevelsPOWithBLOBs selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemberDifferentLevelsPOWithBLOBs record, @Param("example") MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MemberDifferentLevelsPOWithBLOBs record, @Param("example") MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByExample(@Param("record") MemberDifferentLevelsPO record, @Param("example") MemberDifferentLevelsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByPrimaryKeySelective(MemberDifferentLevelsPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(MemberDifferentLevelsPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_different_levels
     *
     * @mbggenerated Sun Nov 17 16:04:44 CST 2019
     */
    int updateByPrimaryKey(MemberDifferentLevelsPO record);

    /**
     * 获取患者本次层级的上一次变化的层级记录
     * @param changeDt
     * @param memberId
     * @return
     */
    MemberDifferentLevelsPO getLastLogByNowLog(@Param("layer") Integer layer,@Param("changeDt") String changeDt, @Param("memberId") String memberId,@Param("originId") String originId);

    /**
     * 获取患者当前的分层分级
     * @param memberId
     * @return
     */
    MemberDifferentLevelsPO getCurrentResultByMid(@Param("memberId") String memberId,@Param("originId") String originId);
}
