package com.comvee.cdms.questionnaire.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_questionnaire
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class QuestionnairePO {
    /**
     * sid
     */
    private String sid;

    /**
     * 问卷类型
     * question_type
     */
    private Integer questionType;

    /**
     * 问卷名称
     * question_name
     */
    private String questionName;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 医生id
     * doctor_id
     */
    private String doctorId;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 问卷状态 1 未填写 2 草稿 3 已完成
     * question_status
     */
    private Integer questionStatus;

    /**
     * 结果的json
     * result_json
     */
    private String resultJson;

    /**
     * 提交时间
     * commit_dt
     */
    private String commitDt;

    /**
     * 问卷内容json
     * content_json
     */
    private String contentJson;

    /**
     * 创建类型创建类型1:问卷管理创建2:自定义随访里面的问卷
     */
    private Integer createType;

    /**
     * 自定义随访内容id
     */
    private String followContentId;

    public Integer getCreateType() {
        return createType;
    }

    public void setCreateType(Integer createType) {
        this.createType = createType;
    }

    public String getFollowContentId() {
        return followContentId;
    }

    public void setFollowContentId(String followContentId) {
        this.followContentId = followContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.sid
     *
     * @return the value of t_questionnaire.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.sid
     *
     * @param sid the value for t_questionnaire.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.question_type
     *
     * @return the value of t_questionnaire.question_type
     *
     * @mbggenerated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.question_type
     *
     * @param questionType the value for t_questionnaire.question_type
     *
     * @mbggenerated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.question_name
     *
     * @return the value of t_questionnaire.question_name
     *
     * @mbggenerated
     */
    public String getQuestionName() {
        return questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.question_name
     *
     * @param questionName the value for t_questionnaire.question_name
     *
     * @mbggenerated
     */
    public void setQuestionName(String questionName) {
        this.questionName = questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.insert_dt
     *
     * @return the value of t_questionnaire.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.insert_dt
     *
     * @param insertDt the value for t_questionnaire.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.update_dt
     *
     * @return the value of t_questionnaire.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.update_dt
     *
     * @param updateDt the value for t_questionnaire.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.member_id
     *
     * @return the value of t_questionnaire.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.member_id
     *
     * @param memberId the value for t_questionnaire.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.doctor_id
     *
     * @return the value of t_questionnaire.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.doctor_id
     *
     * @param doctorId the value for t_questionnaire.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.operator_id
     *
     * @return the value of t_questionnaire.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.operator_id
     *
     * @param operatorId the value for t_questionnaire.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.question_status
     *
     * @return the value of t_questionnaire.question_status
     *
     * @mbggenerated
     */
    public Integer getQuestionStatus() {
        return questionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.question_status
     *
     * @param questionStatus the value for t_questionnaire.question_status
     *
     * @mbggenerated
     */
    public void setQuestionStatus(Integer questionStatus) {
        this.questionStatus = questionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.result_json
     *
     * @return the value of t_questionnaire.result_json
     *
     * @mbggenerated
     */
    public String getResultJson() {
        return resultJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.result_json
     *
     * @param resultJson the value for t_questionnaire.result_json
     *
     * @mbggenerated
     */
    public void setResultJson(String resultJson) {
        this.resultJson = resultJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.commit_dt
     *
     * @return the value of t_questionnaire.commit_dt
     *
     * @mbggenerated
     */
    public String getCommitDt() {
        return commitDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.commit_dt
     *
     * @param commitDt the value for t_questionnaire.commit_dt
     *
     * @mbggenerated
     */
    public void setCommitDt(String commitDt) {
        this.commitDt = commitDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire.content_json
     *
     * @return the value of t_questionnaire.content_json
     *
     * @mbggenerated
     */
    public String getContentJson() {
        return contentJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire.content_json
     *
     * @param contentJson the value for t_questionnaire.content_json
     *
     * @mbggenerated
     */
    public void setContentJson(String contentJson) {
        this.contentJson = contentJson;
    }
}