package com.comvee.cdms.insulinpump.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insulin_pump_observe_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class InsulinPumpObserveRecordPO {
    /**
     * sid
     */
    private String sid;

    /**
     * 患者id
     * member_id
     */
    private String memberId;

    /**
     * 住院号
     * hospital_no
     */
    private String hospitalNo;

    /**
     * 操作者id
     * operator_id
     */
    private String operatorId;

    /**
     * 签名
     * sign
     */
    private String sign;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * 记录日期
     * record_dt
     */
    private String recordDt;

    /**
     * 诊断结果
     * diagnosis
     */
    private String diagnosis;

    /**
     * 数据json
     * data_json
     */
    private String dataJson;

    /**
     * 虚拟病区记录id
     */
    private String virtualWardId;

    private String cardNo;

    public String getCardNo() {
        return cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public String getVirtualWardId() {
        return virtualWardId;
    }

    public void setVirtualWardId(String virtualWardId) {
        this.virtualWardId = virtualWardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.sid
     *
     * @return the value of t_insulin_pump_observe_record.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.sid
     *
     * @param sid the value for t_insulin_pump_observe_record.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.member_id
     *
     * @return the value of t_insulin_pump_observe_record.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.member_id
     *
     * @param memberId the value for t_insulin_pump_observe_record.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.hospital_no
     *
     * @return the value of t_insulin_pump_observe_record.hospital_no
     *
     * @mbggenerated
     */
    public String getHospitalNo() {
        return hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.hospital_no
     *
     * @param hospitalNo the value for t_insulin_pump_observe_record.hospital_no
     *
     * @mbggenerated
     */
    public void setHospitalNo(String hospitalNo) {
        this.hospitalNo = hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.operator_id
     *
     * @return the value of t_insulin_pump_observe_record.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.operator_id
     *
     * @param operatorId the value for t_insulin_pump_observe_record.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.sign
     *
     * @return the value of t_insulin_pump_observe_record.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.sign
     *
     * @param sign the value for t_insulin_pump_observe_record.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.insert_dt
     *
     * @return the value of t_insulin_pump_observe_record.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.insert_dt
     *
     * @param insertDt the value for t_insulin_pump_observe_record.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.update_dt
     *
     * @return the value of t_insulin_pump_observe_record.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.update_dt
     *
     * @param updateDt the value for t_insulin_pump_observe_record.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.valid
     *
     * @return the value of t_insulin_pump_observe_record.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.valid
     *
     * @param valid the value for t_insulin_pump_observe_record.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.record_dt
     *
     * @return the value of t_insulin_pump_observe_record.record_dt
     *
     * @mbggenerated
     */
    public String getRecordDt() {
        return recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.record_dt
     *
     * @param recordDt the value for t_insulin_pump_observe_record.record_dt
     *
     * @mbggenerated
     */
    public void setRecordDt(String recordDt) {
        this.recordDt = recordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.diagnosis
     *
     * @return the value of t_insulin_pump_observe_record.diagnosis
     *
     * @mbggenerated
     */
    public String getDiagnosis() {
        return diagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.diagnosis
     *
     * @param diagnosis the value for t_insulin_pump_observe_record.diagnosis
     *
     * @mbggenerated
     */
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insulin_pump_observe_record.data_json
     *
     * @return the value of t_insulin_pump_observe_record.data_json
     *
     * @mbggenerated
     */
    public String getDataJson() {
        return dataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insulin_pump_observe_record.data_json
     *
     * @param dataJson the value for t_insulin_pump_observe_record.data_json
     *
     * @mbggenerated
     */
    public void setDataJson(String dataJson) {
        this.dataJson = dataJson;
    }
}