package com.comvee.cdms.complication.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_screening_item_dict
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ScreeningItemDictPO {
    /**
     * sid
     */
    private String sid;

    /**
     * item_name
     */
    private String itemName;

    /**
     * item_value
     */
    private Integer itemValue;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_item_dict.sid
     *
     * @return the value of t_screening_item_dict.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_item_dict.sid
     *
     * @param sid the value for t_screening_item_dict.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_item_dict.item_name
     *
     * @return the value of t_screening_item_dict.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_item_dict.item_name
     *
     * @param itemName the value for t_screening_item_dict.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_item_dict.item_value
     *
     * @return the value of t_screening_item_dict.item_value
     *
     * @mbggenerated
     */
    public Integer getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_item_dict.item_value
     *
     * @param itemValue the value for t_screening_item_dict.item_value
     *
     * @mbggenerated
     */
    public void setItemValue(Integer itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_item_dict.update_dt
     *
     * @return the value of t_screening_item_dict.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_item_dict.update_dt
     *
     * @param updateDt the value for t_screening_item_dict.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_item_dict.insert_dt
     *
     * @return the value of t_screening_item_dict.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_item_dict.insert_dt
     *
     * @param insertDt the value for t_screening_item_dict.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }
}