package com.comvee.cdms.complication.model.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_screening_stats
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ScreeningStatsPO {
    /**
     * sid
     */
    private String sid;

    /**
     * id_card
     */
    private String idCard;

    /**
     * item_code
     */
    private String itemCode;

    /**
     * item_value
     */
    private String itemValue;

    /**
     * insert_dt
     */
    private String insertDt;

    /**
     * update_dt
     */
    private String updateDt;

    /**
     * valid
     */
    private Integer valid;

    /**
     * member_id
     */
    private String memberId;

    /**
     * doctor_id
     */
    private String doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.sid
     *
     * @return the value of t_screening_stats.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.sid
     *
     * @param sid the value for t_screening_stats.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.id_card
     *
     * @return the value of t_screening_stats.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.id_card
     *
     * @param idCard the value for t_screening_stats.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.item_code
     *
     * @return the value of t_screening_stats.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.item_code
     *
     * @param itemCode the value for t_screening_stats.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.item_value
     *
     * @return the value of t_screening_stats.item_value
     *
     * @mbggenerated
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.item_value
     *
     * @param itemValue the value for t_screening_stats.item_value
     *
     * @mbggenerated
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.insert_dt
     *
     * @return the value of t_screening_stats.insert_dt
     *
     * @mbggenerated
     */
    public String getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.insert_dt
     *
     * @param insertDt the value for t_screening_stats.insert_dt
     *
     * @mbggenerated
     */
    public void setInsertDt(String insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.update_dt
     *
     * @return the value of t_screening_stats.update_dt
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.update_dt
     *
     * @param updateDt the value for t_screening_stats.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.valid
     *
     * @return the value of t_screening_stats.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.valid
     *
     * @param valid the value for t_screening_stats.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.member_id
     *
     * @return the value of t_screening_stats.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.member_id
     *
     * @param memberId the value for t_screening_stats.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screening_stats.doctor_id
     *
     * @return the value of t_screening_stats.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screening_stats.doctor_id
     *
     * @param doctorId the value for t_screening_stats.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
}