package com.comvee.cdms.questionnaire.model.dto;

import javax.validation.constraints.NotEmpty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_questionnaire
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SaveQuestionnaireDTO {
    /**
     * sid
     */
    @NotEmpty
    private String sid;

    /**
     * 结果的json
     * result_json
     */
    private String resultJson;

    /**
     * 问卷内容json
     * content_json
     */
    @NotEmpty
    private String contentJson;

    private Integer questionStatus;

    public Integer getQuestionStatus() {
        return questionStatus;
    }

    public void setQuestionStatus(Integer questionStatus) {
        this.questionStatus = questionStatus;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getResultJson() {
        return resultJson;
    }

    public void setResultJson(String resultJson) {
        this.resultJson = resultJson;
    }

    public String getContentJson() {
        return contentJson;
    }

    public void setContentJson(String contentJson) {
        this.contentJson = contentJson;
    }
}